-- Migration: Seed initial criteria votes for all dishes
-- Created: 2026-04-15
-- Votes for potato dishes as generated by GLM-5

INSERT INTO dish_criteria_votes (id, dish_id, criterion_id, score, created_at) VALUES
-- Mashed Potatoes (a1b2c3d4-e5f6-7890-abcd-ef1234567890)
('v001', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'crispiness', -4.0, unixepoch()),
('v002', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'richness', 3.5, unixepoch()),
('v003', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'flavor_complexity', -2.0, unixepoch()),
('v004', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'heartiness', 2.0, unixepoch()),
('v005', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'potato_prominence', 5.0, unixepoch()),
('v006', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'novelty', -4.0, unixepoch()),
('v007', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'elegance', -1.0, unixepoch()),
('v008', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'customizability', 2.5, unixepoch()),

-- French Fries (b2c3d4e5-f6a7-8901-bcde-f12345678901)
('v009', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'crispiness', 4.5, unixepoch()),
('v010', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'richness', 1.0, unixepoch()),
('v011', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'flavor_complexity', -1.5, unixepoch()),
('v012', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'heartiness', -1.0, unixepoch()),
('v013', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'potato_prominence', 5.0, unixepoch()),
('v014', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'novelty', -5.0, unixepoch()),
('v015', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'elegance', -3.0, unixepoch()),
('v016', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'customizability', 4.0, unixepoch()),

-- Baked Potato (c3d4e5f6-a7b8-9012-cdef-123456789012)
('v017', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'crispiness', -1.0, unixepoch()),
('v018', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'richness', -1.5, unixepoch()),
('v019', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'flavor_complexity', -3.5, unixepoch()),
('v020', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'heartiness', 1.5, unixepoch()),
('v021', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'potato_prominence', 5.0, unixepoch()),
('v022', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'novelty', -4.5, unixepoch()),
('v023', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'elegance', -2.0, unixepoch()),
('v024', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'customizability', 5.0, unixepoch()),

-- Potato Soup (d4e5f6a7-b8c9-0123-def1-234567890123)
('v025', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'crispiness', -4.5, unixepoch()),
('v026', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'richness', 2.5, unixepoch()),
('v027', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'flavor_complexity', -1.0, unixepoch()),
('v028', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'heartiness', 3.0, unixepoch()),
('v029', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'potato_prominence', 4.0, unixepoch()),
('v030', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'novelty', -3.0, unixepoch()),
('v031', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'elegance', -0.5, unixepoch()),
('v032', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'customizability', 1.0, unixepoch()),

-- Potato Salad (e5f6a7b8-c9d0-1234-ef12-345678901234)
('v033', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'crispiness', -3.0, unixepoch()),
('v034', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'richness', 0.0, unixepoch()),
('v035', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'flavor_complexity', -0.5, unixepoch()),
('v036', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'heartiness', -1.5, unixepoch()),
('v037', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'potato_prominence', 4.5, unixepoch()),
('v038', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'novelty', -3.5, unixepoch()),
('v039', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'elegance', -2.5, unixepoch()),
('v040', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'customizability', 2.0, unixepoch()),

-- Hash Browns (f6a7b8c9-d0e1-2345-f123-456789012345)
('v041', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'crispiness', 4.0, unixepoch()),
('v042', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'richness', 1.5, unixepoch()),
('v043', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'flavor_complexity', -2.0, unixepoch()),
('v044', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'heartiness', -1.5, unixepoch()),
('v045', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'potato_prominence', 4.5, unixepoch()),
('v046', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'novelty', -3.0, unixepoch()),
('v047', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'elegance', -3.5, unixepoch()),
('v048', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'customizability', 0.5, unixepoch()),

-- Potato Gratin (a7b8c9d0-e1f2-3456-1234-567890123456)
('v049', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'crispiness', 0.5, unixepoch()),
('v050', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'richness', 4.5, unixepoch()),
('v051', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'flavor_complexity', 0.5, unixepoch()),
('v052', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'heartiness', 3.5, unixepoch()),
('v053', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'potato_prominence', 4.5, unixepoch()),
('v054', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'novelty', -2.0, unixepoch()),
('v055', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'elegance', 1.5, unixepoch()),
('v056', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'customizability', -1.5, unixepoch()),

-- Shepherd's Pie (b8c9d0e1-f2a3-4567-2345-678901234567)
('v057', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'crispiness', -2.0, unixepoch()),
('v058', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'richness', 3.0, unixepoch()),
('v059', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'flavor_complexity', 1.5, unixepoch()),
('v060', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'heartiness', 5.0, unixepoch()),
('v061', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'potato_prominence', 3.0, unixepoch()),
('v062', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'novelty', -2.5, unixepoch()),
('v063', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'elegance', 0.0, unixepoch()),
('v064', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'customizability', 0.5, unixepoch()),

-- Potato Gnocchi (c9d0e1f2-a3b4-5678-3456-789012345678)
('v065', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'crispiness', -3.5, unixepoch()),
('v066', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'richness', 2.0, unixepoch()),
('v067', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'flavor_complexity', 0.0, unixepoch()),
('v068', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'heartiness', 2.5, unixepoch()),
('v069', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'potato_prominence', 4.0, unixepoch()),
('v070', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'novelty', -1.5, unixepoch()),
('v071', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'elegance', 1.0, unixepoch()),
('v072', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'customizability', -1.0, unixepoch()),

-- Potato Latkes (d0e1f2a3-b4c5-6789-4567-890123456789)
('v073', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'crispiness', 4.0, unixepoch()),
('v074', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'richness', 2.0, unixepoch()),
('v075', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'flavor_complexity', -0.5, unixepoch()),
('v076', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'heartiness', 0.0, unixepoch()),
('v077', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'potato_prominence', 4.5, unixepoch()),
('v078', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'novelty', -1.0, unixepoch()),
('v079', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'elegance', -1.5, unixepoch()),
('v080', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'customizability', 1.0, unixepoch()),

-- Potato Wedges (a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e)
('v081', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'crispiness', 3.5, unixepoch()),
('v082', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'richness', 0.5, unixepoch()),
('v083', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'flavor_complexity', -1.0, unixepoch()),
('v084', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'heartiness', -0.5, unixepoch()),
('v085', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'potato_prominence', 4.5, unixepoch()),
('v086', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'novelty', -4.0, unixepoch()),
('v087', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'elegance', -3.5, unixepoch()),
('v088', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'customizability', 1.5, unixepoch()),

-- Scalloped Potatoes (b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f)
('v089', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'crispiness', -1.5, unixepoch()),
('v090', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'richness', 4.0, unixepoch()),
('v091', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'flavor_complexity', 0.0, unixepoch()),
('v092', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'heartiness', 3.0, unixepoch()),
('v093', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'potato_prominence', 5.0, unixepoch()),
('v094', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'novelty', -2.5, unixepoch()),
('v095', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'elegance', 0.5, unixepoch()),
('v096', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'customizability', -1.5, unixepoch()),

-- Potato Skins (c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a)
('v097', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'crispiness', 4.0, unixepoch()),
('v098', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'richness', 2.5, unixepoch()),
('v099', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'flavor_complexity', 0.5, unixepoch()),
('v100', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'heartiness', 0.0, unixepoch()),
('v101', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'potato_prominence', 3.5, unixepoch()),
('v102', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'novelty', -2.0, unixepoch()),
('v103', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'elegance', -3.0, unixepoch()),
('v104', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'customizability', 4.5, unixepoch()),

-- Tater Tots (d0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b)
('v105', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'crispiness', 4.5, unixepoch()),
('v106', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'richness', 1.5, unixepoch()),
('v107', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'flavor_complexity', -2.5, unixepoch()),
('v108', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'heartiness', -2.0, unixepoch()),
('v109', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'potato_prominence', 4.0, unixepoch()),
('v110', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'novelty', -3.0, unixepoch()),
('v111', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'elegance', -4.5, unixepoch()),
('v112', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'customizability', 0.5, unixepoch()),

-- Potato Chips (e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c)
('v113', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'crispiness', 5.0, unixepoch()),
('v114', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'richness', 0.5, unixepoch()),
('v115', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'flavor_complexity', -0.5, unixepoch()),
('v116', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'heartiness', -4.0, unixepoch()),
('v117', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'potato_prominence', 4.5, unixepoch()),
('v118', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'novelty', -4.5, unixepoch()),
('v119', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'elegance', -3.0, unixepoch()),
('v120', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'customizability', 2.0, unixepoch()),

-- Roasted Potatoes (f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d)
('v121', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'crispiness', 3.0, unixepoch()),
('v122', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'richness', 1.0, unixepoch()),
('v123', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'flavor_complexity', -0.5, unixepoch()),
('v124', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'heartiness', 1.0, unixepoch()),
('v125', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'potato_prominence', 5.0, unixepoch()),
('v126', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'novelty', -3.5, unixepoch()),
('v127', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'elegance', -0.5, unixepoch()),
('v128', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'customizability', 1.5, unixepoch()),

-- Potato Pancakes (a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e)
('v129', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'crispiness', 3.5, unixepoch()),
('v130', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'richness', 1.5, unixepoch()),
('v131', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'flavor_complexity', -1.0, unixepoch()),
('v132', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'heartiness', -0.5, unixepoch()),
('v133', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'potato_prominence', 4.5, unixepoch()),
('v134', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'novelty', -2.0, unixepoch()),
('v135', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'elegance', -2.0, unixepoch()),
('v136', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'customizability', 0.5, unixepoch()),

-- Colcannon (b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f)
('v137', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'crispiness', -3.5, unixepoch()),
('v138', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'richness', 2.0, unixepoch()),
('v139', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'flavor_complexity', 0.0, unixepoch()),
('v140', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'heartiness', 2.5, unixepoch()),
('v141', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'potato_prominence', 4.0, unixepoch()),
('v142', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'novelty', -0.5, unixepoch()),
('v143', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'elegance', -1.5, unixepoch()),
('v144', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'customizability', 0.0, unixepoch()),

-- Boxty (c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a)
('v145', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'crispiness', 2.5, unixepoch()),
('v146', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'richness', 1.0, unixepoch()),
('v147', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'flavor_complexity', -1.0, unixepoch()),
('v148', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'heartiness', 0.5, unixepoch()),
('v149', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'potato_prominence', 5.0, unixepoch()),
('v150', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'novelty', 1.5, unixepoch()),
('v151', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'elegance', -1.5, unixepoch()),
('v152', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'customizability', 0.5, unixepoch()),

-- Potato Croquettes (d6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b)
('v153', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'crispiness', 3.5, unixepoch()),
('v154', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'richness', 2.5, unixepoch()),
('v155', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'flavor_complexity', -0.5, unixepoch()),
('v156', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'heartiness', 0.0, unixepoch()),
('v157', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'potato_prominence', 4.0, unixepoch()),
('v158', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'novelty', -1.0, unixepoch()),
('v159', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'elegance', 0.5, unixepoch()),
('v160', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'customizability', -1.0, unixepoch()),

-- Patatas Bravas (e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c)
('v161', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'crispiness', 3.5, unixepoch()),
('v162', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'richness', 1.0, unixepoch()),
('v163', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'flavor_complexity', 2.0, unixepoch()),
('v164', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'heartiness', 1.0, unixepoch()),
('v165', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'potato_prominence', 4.5, unixepoch()),
('v166', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'novelty', -1.5, unixepoch()),
('v167', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'elegance', -1.0, unixepoch()),
('v168', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'customizability', -2.0, unixepoch()),

-- Potato Curry (f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d)
('v169', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'crispiness', -3.0, unixepoch()),
('v170', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'richness', 1.5, unixepoch()),
('v171', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'flavor_complexity', 3.5, unixepoch()),
('v172', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'heartiness', 3.5, unixepoch()),
('v173', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'potato_prominence', 3.5, unixepoch()),
('v174', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'novelty', -1.0, unixepoch()),
('v175', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'elegance', -1.5, unixepoch()),
('v176', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'customizability', 0.0, unixepoch()),

-- Spanish Tortilla (a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e)
('v177', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'crispiness', -2.0, unixepoch()),
('v178', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'richness', 1.5, unixepoch()),
('v179', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'flavor_complexity', 0.5, unixepoch()),
('v180', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'heartiness', 2.5, unixepoch()),
('v181', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'potato_prominence', 4.0, unixepoch()),
('v182', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'novelty', -1.0, unixepoch()),
('v183', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'elegance', 0.0, unixepoch()),
('v184', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'customizability', -2.0, unixepoch()),

-- Potato Rosti (b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f)
('v185', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'crispiness', 3.5, unixepoch()),
('v186', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'richness', 1.5, unixepoch()),
('v187', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'flavor_complexity', -1.5, unixepoch()),
('v188', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'heartiness', 1.0, unixepoch()),
('v189', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'potato_prominence', 5.0, unixepoch()),
('v190', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'novelty', 0.5, unixepoch()),
('v191', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'elegance', 0.5, unixepoch()),
('v192', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'customizability', -0.5, unixepoch()),

-- Funeral Potatoes (c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c)
('v193', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'crispiness', 2.0, unixepoch()),
('v194', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'richness', 4.5, unixepoch()),
('v195', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'flavor_complexity', 0.5, unixepoch()),
('v196', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'heartiness', 3.5, unixepoch()),
('v197', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'potato_prominence', 3.5, unixepoch()),
('v198', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'novelty', 1.0, unixepoch()),
('v199', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'elegance', -2.5, unixepoch()),
('v200', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'customizability', 0.0, unixepoch()),

-- Potato Leek Soup (d2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d)
('v201', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'crispiness', -4.5, unixepoch()),
('v202', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'richness', 2.5, unixepoch()),
('v203', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'flavor_complexity', 0.5, unixepoch()),
('v204', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'heartiness', 2.5, unixepoch()),
('v205', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'potato_prominence', 3.5, unixepoch()),
('v206', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'novelty', -2.0, unixepoch()),
('v207', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'elegance', 0.5, unixepoch()),
('v208', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'customizability', -0.5, unixepoch()),

-- Pommes Anna (e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e)
('v209', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'crispiness', 1.0, unixepoch()),
('v210', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'richness', 4.0, unixepoch()),
('v211', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'flavor_complexity', -1.0, unixepoch()),
('v212', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'heartiness', 2.5, unixepoch()),
('v213', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'potato_prominence', 5.0, unixepoch()),
('v214', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'novelty', 1.5, unixepoch()),
('v215', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'elegance', 3.5, unixepoch()),
('v216', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'customizability', -3.0, unixepoch()),

-- Potato Pierogi (f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f)
('v217', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'crispiness', -2.5, unixepoch()),
('v218', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'richness', 2.0, unixepoch()),
('v219', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'flavor_complexity', 0.0, unixepoch()),
('v220', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'heartiness', 2.5, unixepoch()),
('v221', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'potato_prominence', 4.0, unixepoch()),
('v222', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'novelty', -0.5, unixepoch()),
('v223', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'elegance', -0.5, unixepoch()),
('v224', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'customizability', -1.0, unixepoch()),

-- Sweet Potato Fries (a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a)
('v225', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'crispiness', 4.0, unixepoch()),
('v226', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'richness', 0.5, unixepoch()),
('v227', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'flavor_complexity', -0.5, unixepoch()),
('v228', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'heartiness', -1.0, unixepoch()),
('v229', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'potato_prominence', 2.0, unixepoch()),
('v230', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'novelty', -2.5, unixepoch()),
('v231', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'elegance', -2.5, unixepoch()),
('v232', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'customizability', 2.5, unixepoch()),

-- Twice Baked Potatoes (b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b)
('v233', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'crispiness', 0.0, unixepoch()),
('v234', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'richness', 3.0, unixepoch()),
('v235', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'flavor_complexity', 0.5, unixepoch()),
('v236', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'heartiness', 2.5, unixepoch()),
('v237', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'potato_prominence', 4.5, unixepoch()),
('v238', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'novelty', -2.0, unixepoch()),
('v239', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'elegance', 0.0, unixepoch()),
('v240', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'customizability', 3.5, unixepoch()),

-- Ajiaco (785539f6-98be-4a22-8033-3f28d8396149)
('v241', '785539f6-98be-4a22-8033-3f28d8396149', 'crispiness', -4.0, unixepoch()),
('v242', '785539f6-98be-4a22-8033-3f28d8396149', 'richness', 2.0, unixepoch()),
('v243', '785539f6-98be-4a22-8033-3f28d8396149', 'flavor_complexity', 2.0, unixepoch()),
('v244', '785539f6-98be-4a22-8033-3f28d8396149', 'heartiness', 3.5, unixepoch()),
('v245', '785539f6-98be-4a22-8033-3f28d8396149', 'potato_prominence', 4.0, unixepoch()),
('v246', '785539f6-98be-4a22-8033-3f28d8396149', 'novelty', 3.0, unixepoch()),
('v247', '785539f6-98be-4a22-8033-3f28d8396149', 'elegance', 0.0, unixepoch()),
('v248', '785539f6-98be-4a22-8033-3f28d8396149', 'customizability', -0.5, unixepoch()),

-- Aligot (be4f8c34-64f7-47be-822c-2f00a22977b3)
('v249', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'crispiness', -4.5, unixepoch()),
('v250', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'richness', 5.0, unixepoch()),
('v251', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'flavor_complexity', 0.5, unixepoch()),
('v252', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'heartiness', 2.5, unixepoch()),
('v253', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'potato_prominence', 4.0, unixepoch()),
('v254', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'novelty', 2.5, unixepoch()),
('v255', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'elegance', 1.5, unixepoch()),
('v256', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'customizability', -2.0, unixepoch()),

-- Aloo gobi (436e323b-4898-4fd7-892c-9798d81f35ae)
('v257', '436e323b-4898-4fd7-892c-9798d81f35ae', 'crispiness', -2.0, unixepoch()),
('v258', '436e323b-4898-4fd7-892c-9798d81f35ae', 'richness', 0.0, unixepoch()),
('v259', '436e323b-4898-4fd7-892c-9798d81f35ae', 'flavor_complexity', 3.5, unixepoch()),
('v260', '436e323b-4898-4fd7-892c-9798d81f35ae', 'heartiness', 2.5, unixepoch()),
('v261', '436e323b-4898-4fd7-892c-9798d81f35ae', 'potato_prominence', 3.5, unixepoch()),
('v262', '436e323b-4898-4fd7-892c-9798d81f35ae', 'novelty', -0.5, unixepoch()),
('v263', '436e323b-4898-4fd7-892c-9798d81f35ae', 'elegance', -1.0, unixepoch()),
('v264', '436e323b-4898-4fd7-892c-9798d81f35ae', 'customizability', -0.5, unixepoch()),

-- Aloo gosht (9d6cfd5e-2d85-40b5-b746-de51e8fd04e1)
('v265', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'crispiness', -3.0, unixepoch()),
('v266', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'richness', 2.0, unixepoch()),
('v267', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'flavor_complexity', 2.5, unixepoch()),
('v268', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'heartiness', 4.0, unixepoch()),
('v269', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'potato_prominence', 2.5, unixepoch()),
('v270', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'novelty', 0.5, unixepoch()),
('v271', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'elegance', -1.5, unixepoch()),
('v272', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'customizability', 0.0, unixepoch()),

-- Aloo pie (d7336300-3d6f-48bb-be6d-c68aa24d29f6)
('v273', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'crispiness', 1.5, unixepoch()),
('v274', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'richness', 1.5, unixepoch()),
('v275', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'flavor_complexity', 1.5, unixepoch()),
('v276', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'heartiness', 1.5, unixepoch()),
('v277', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'potato_prominence', 3.5, unixepoch()),
('v278', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'novelty', 3.0, unixepoch()),
('v279', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'elegance', -3.0, unixepoch()),
('v280', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'customizability', -1.5, unixepoch()),

-- Aloo posto (3f384d4d-bc42-4c46-a5b8-54b30477efee)
('v281', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'crispiness', -3.0, unixepoch()),
('v282', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'richness', 1.5, unixepoch()),
('v283', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'flavor_complexity', 2.5, unixepoch()),
('v284', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'heartiness', 1.5, unixepoch()),
('v285', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'potato_prominence', 4.5, unixepoch()),
('v286', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'novelty', 3.5, unixepoch()),
('v287', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'elegance', -0.5, unixepoch()),
('v288', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'customizability', -2.0, unixepoch()),

-- Älplermagronen (fd9ba604-89ec-42cb-8811-e78252f80690)
('v289', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'crispiness', -2.5, unixepoch()),
('v290', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'richness', 3.5, unixepoch()),
('v291', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'flavor_complexity', 0.5, unixepoch()),
('v292', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'heartiness', 4.0, unixepoch()),
('v293', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'potato_prominence', 2.5, unixepoch()),
('v294', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'novelty', 2.5, unixepoch()),
('v295', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'elegance', 0.0, unixepoch()),
('v296', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'customizability', -1.0, unixepoch()),

-- Bangers and mash (8b53de88-0b2e-43b3-956c-78ec3f15c73c)
('v297', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'crispiness', -3.5, unixepoch()),
('v298', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'richness', 3.0, unixepoch()),
('v299', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'flavor_complexity', 1.0, unixepoch()),
('v300', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'heartiness', 4.0, unixepoch()),
('v301', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'potato_prominence', 3.0, unixepoch()),
('v302', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'novelty', -1.5, unixepoch()),
('v303', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'elegance', -2.0, unixepoch()),
('v304', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'customizability', 0.0, unixepoch()),

-- Batatas a murro (989ff929-8368-4914-8645-e2007ca7106c)
('v305', '989ff929-8368-4914-8645-e2007ca7106c', 'crispiness', 1.5, unixepoch()),
('v306', '989ff929-8368-4914-8645-e2007ca7106c', 'richness', -2.0, unixepoch()),
('v307', '989ff929-8368-4914-8645-e2007ca7106c', 'flavor_complexity', 0.0, unixepoch()),
('v308', '989ff929-8368-4914-8645-e2007ca7106c', 'heartiness', 1.0, unixepoch()),
('v309', '989ff929-8368-4914-8645-e2007ca7106c', 'potato_prominence', 5.0, unixepoch()),
('v310', '989ff929-8368-4914-8645-e2007ca7106c', 'novelty', 2.5, unixepoch()),
('v311', '989ff929-8368-4914-8645-e2007ca7106c', 'elegance', 0.0, unixepoch()),
('v312', '989ff929-8368-4914-8645-e2007ca7106c', 'customizability', -2.0, unixepoch()),

-- Batata harra (4d88aa81-4a81-496e-b1d2-234a732098b9)
('v313', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'crispiness', 2.5, unixepoch()),
('v314', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'richness', 0.5, unixepoch()),
('v315', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'flavor_complexity', 2.5, unixepoch()),
('v316', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'heartiness', 0.5, unixepoch()),
('v317', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'potato_prominence', 4.5, unixepoch()),
('v318', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'novelty', 2.0, unixepoch()),
('v319', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'elegance', -1.5, unixepoch()),
('v320', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'customizability', -1.5, unixepoch()),

-- Batata vada (0dd436f4-100e-4818-8744-e4e0ea31c4d8)
('v321', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'crispiness', 3.5, unixepoch()),
('v322', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'richness', 1.0, unixepoch()),
('v323', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'flavor_complexity', 1.5, unixepoch()),
('v324', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'heartiness', -1.0, unixepoch()),
('v325', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'potato_prominence', 4.0, unixepoch()),
('v326', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'novelty', 1.5, unixepoch()),
('v327', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'elegance', -2.5, unixepoch()),
('v328', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'customizability', -2.0, unixepoch()),

-- Batates bechamel (327177e9-8641-40ef-89bd-1cbf1c2387d3)
('v329', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'crispiness', -2.5, unixepoch()),
('v330', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'richness', 3.5, unixepoch()),
('v331', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'flavor_complexity', 1.0, unixepoch()),
('v332', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'heartiness', 4.0, unixepoch()),
('v333', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'potato_prominence', 3.0, unixepoch()),
('v334', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'novelty', 2.5, unixepoch()),
('v335', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'elegance', 0.0, unixepoch()),
('v336', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'customizability', -1.5, unixepoch()),

-- Bauernfrühstück (ae5c5502-480d-4aeb-8b7e-73380f10bd1f)
('v337', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'crispiness', 2.0, unixepoch()),
('v338', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'richness', 2.5, unixepoch()),
('v339', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'flavor_complexity', 0.5, unixepoch()),
('v340', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'heartiness', 3.5, unixepoch()),
('v341', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'potato_prominence', 3.0, unixepoch()),
('v342', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'novelty', 1.5, unixepoch()),
('v343', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'elegance', -2.5, unixepoch()),
('v344', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'customizability', 0.5, unixepoch()),

-- Bombay potatoes (6d06d0e8-6907-4311-931b-13af3a7b81c7)
('v345', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'crispiness', 1.0, unixepoch()),
('v346', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'richness', 1.0, unixepoch()),
('v347', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'flavor_complexity', 3.0, unixepoch()),
('v348', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'heartiness', 1.5, unixepoch()),
('v349', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'potato_prominence', 4.5, unixepoch()),
('v350', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'novelty', -0.5, unixepoch()),
('v351', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'elegance', -1.5, unixepoch()),
('v352', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'customizability', -0.5, unixepoch()),

-- Boulangère potatoes (3a9926a1-69b6-475f-83dc-99817faa9ad2)
('v353', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'crispiness', -1.0, unixepoch()),
('v354', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'richness', 2.0, unixepoch()),
('v355', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'flavor_complexity', 0.5, unixepoch()),
('v356', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'heartiness', 2.5, unixepoch()),
('v357', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'potato_prominence', 4.5, unixepoch()),
('v358', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'novelty', 1.5, unixepoch()),
('v359', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'elegance', 1.0, unixepoch()),
('v360', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'customizability', -2.0, unixepoch()),

-- Bonda (a475c9b3-1419-42d9-82be-237d58a79a8d)
('v361', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'crispiness', 3.0, unixepoch()),
('v362', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'richness', 1.5, unixepoch()),
('v363', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'flavor_complexity', 2.0, unixepoch()),
('v364', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'heartiness', -1.0, unixepoch()),
('v365', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'potato_prominence', 3.5, unixepoch()),
('v366', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'novelty', 2.5, unixepoch()),
('v367', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'elegance', -2.5, unixepoch()),
('v368', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'customizability', -2.0, unixepoch()),

-- Bubble and squeak (0358bec7-de8b-4fc4-a222-294b01fa90f7)
('v369', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'crispiness', 2.5, unixepoch()),
('v370', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'richness', 1.5, unixepoch()),
('v371', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'flavor_complexity', -0.5, unixepoch()),
('v372', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'heartiness', 2.0, unixepoch()),
('v373', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'potato_prominence', 3.5, unixepoch()),
('v374', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'novelty', -0.5, unixepoch()),
('v375', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'elegance', -3.0, unixepoch()),
('v376', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'customizability', 1.0, unixepoch()),

-- Cacasse à cul nu (40c52835-9537-453f-8093-71a324979dfe)
('v377', '40c52835-9537-453f-8093-71a324979dfe', 'crispiness', -2.5, unixepoch()),
('v378', '40c52835-9537-453f-8093-71a324979dfe', 'richness', 2.5, unixepoch()),
('v379', '40c52835-9537-453f-8093-71a324979dfe', 'flavor_complexity', 0.0, unixepoch()),
('v380', '40c52835-9537-453f-8093-71a324979dfe', 'heartiness', 4.0, unixepoch()),
('v381', '40c52835-9537-453f-8093-71a324979dfe', 'potato_prominence', 4.0, unixepoch()),
('v382', '40c52835-9537-453f-8093-71a324979dfe', 'novelty', 4.0, unixepoch()),
('v383', '40c52835-9537-453f-8093-71a324979dfe', 'elegance', -2.5, unixepoch()),
('v384', '40c52835-9537-453f-8093-71a324979dfe', 'customizability', -1.0, unixepoch()),

-- Canarian wrinkly potatoes (b3515faf-60f3-4c74-8f26-aeb9933a08dd)
('v385', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'crispiness', 0.5, unixepoch()),
('v386', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'richness', -1.0, unixepoch()),
('v387', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'flavor_complexity', 1.0, unixepoch()),
('v388', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'heartiness', 1.0, unixepoch()),
('v389', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'potato_prominence', 5.0, unixepoch()),
('v390', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'novelty', 1.5, unixepoch()),
('v391', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'elegance', 0.0, unixepoch()),
('v392', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'customizability', -2.5, unixepoch()),

-- Carne asada fries (9f2bd161-4945-434b-ac8e-afb036295973)
('v393', '9f2bd161-4945-434b-ac8e-afb036295973', 'crispiness', 3.5, unixepoch()),
('v394', '9f2bd161-4945-434b-ac8e-afb036295973', 'richness', 2.5, unixepoch()),
('v395', '9f2bd161-4945-434b-ac8e-afb036295973', 'flavor_complexity', 1.5, unixepoch()),
('v396', '9f2bd161-4945-434b-ac8e-afb036295973', 'heartiness', 2.5, unixepoch()),
('v397', '9f2bd161-4945-434b-ac8e-afb036295973', 'potato_prominence', 2.5, unixepoch()),
('v398', '9f2bd161-4945-434b-ac8e-afb036295973', 'novelty', -1.0, unixepoch()),
('v399', '9f2bd161-4945-434b-ac8e-afb036295973', 'elegance', -4.0, unixepoch()),
('v400', '9f2bd161-4945-434b-ac8e-afb036295973', 'customizability', 1.5, unixepoch()),

-- Cepelinai (c8488053-7889-4d0b-aa4d-13ee5c7743d2)
('v401', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'crispiness', -3.0, unixepoch()),
('v402', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'richness', 2.5, unixepoch()),
('v403', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'flavor_complexity', 0.5, unixepoch()),
('v404', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'heartiness', 4.0, unixepoch()),
('v405', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'potato_prominence', 4.0, unixepoch()),
('v406', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'novelty', 3.5, unixepoch()),
('v407', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'elegance', -1.0, unixepoch()),
('v408', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'customizability', -2.5, unixepoch()),

-- Chapalele (7d0db129-ad99-4d33-8b21-de28c116b181)
('v409', '7d0db129-ad99-4d33-8b21-de28c116b181', 'crispiness', -2.5, unixepoch()),
('v410', '7d0db129-ad99-4d33-8b21-de28c116b181', 'richness', 1.5, unixepoch()),
('v411', '7d0db129-ad99-4d33-8b21-de28c116b181', 'flavor_complexity', -1.0, unixepoch()),
('v412', '7d0db129-ad99-4d33-8b21-de28c116b181', 'heartiness', 2.0, unixepoch()),
('v413', '7d0db129-ad99-4d33-8b21-de28c116b181', 'potato_prominence', 4.5, unixepoch()),
('v414', '7d0db129-ad99-4d33-8b21-de28c116b181', 'novelty', 4.0, unixepoch()),
('v415', '7d0db129-ad99-4d33-8b21-de28c116b181', 'elegance', -1.5, unixepoch()),
('v416', '7d0db129-ad99-4d33-8b21-de28c116b181', 'customizability', -2.0, unixepoch()),

-- Cheese fries (3b25a411-326c-4a1d-bec4-d24232179a48)
('v417', '3b25a411-326c-4a1d-bec4-d24232179a48', 'crispiness', 3.5, unixepoch()),
('v418', '3b25a411-326c-4a1d-bec4-d24232179a48', 'richness', 3.0, unixepoch()),
('v419', '3b25a411-326c-4a1d-bec4-d24232179a48', 'flavor_complexity', -0.5, unixepoch()),
('v420', '3b25a411-326c-4a1d-bec4-d24232179a48', 'heartiness', 1.0, unixepoch()),
('v421', '3b25a411-326c-4a1d-bec4-d24232179a48', 'potato_prominence', 3.0, unixepoch()),
('v422', '3b25a411-326c-4a1d-bec4-d24232179a48', 'novelty', -3.0, unixepoch()),
('v423', '3b25a411-326c-4a1d-bec4-d24232179a48', 'elegance', -4.0, unixepoch()),
('v424', '3b25a411-326c-4a1d-bec4-d24232179a48', 'customizability', 1.5, unixepoch()),

-- Chips and dip (6a861229-6712-4b8a-a154-8144a8bca88c)
('v425', '6a861229-6712-4b8a-a154-8144a8bca88c', 'crispiness', 5.0, unixepoch()),
('v426', '6a861229-6712-4b8a-a154-8144a8bca88c', 'richness', 1.0, unixepoch()),
('v427', '6a861229-6712-4b8a-a154-8144a8bca88c', 'flavor_complexity', 0.5, unixepoch()),
('v428', '6a861229-6712-4b8a-a154-8144a8bca88c', 'heartiness', -3.5, unixepoch()),
('v429', '6a861229-6712-4b8a-a154-8144a8bca88c', 'potato_prominence', 3.0, unixepoch()),
('v430', '6a861229-6712-4b8a-a154-8144a8bca88c', 'novelty', -3.5, unixepoch()),
('v431', '6a861229-6712-4b8a-a154-8144a8bca88c', 'elegance', -3.0, unixepoch()),
('v432', '6a861229-6712-4b8a-a154-8144a8bca88c', 'customizability', 3.0, unixepoch()),

-- Chocolate-covered potato chips (c868b277-1c62-4b89-8343-90e35e2da9d4)
('v433', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'crispiness', 4.0, unixepoch()),
('v434', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'richness', 2.0, unixepoch()),
('v435', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'flavor_complexity', 0.5, unixepoch()),
('v436', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'heartiness', -4.5, unixepoch()),
('v437', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'potato_prominence', 2.5, unixepoch()),
('v438', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'novelty', 2.0, unixepoch()),
('v439', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'elegance', -1.5, unixepoch()),
('v440', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'customizability', -3.0, unixepoch()),

-- Chorrillana (ee91cd60-3c05-43c1-9fa9-7a725f68b35a)
('v441', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'crispiness', 3.5, unixepoch()),
('v442', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'richness', 3.0, unixepoch()),
('v443', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'flavor_complexity', 1.0, unixepoch()),
('v444', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'heartiness', 4.5, unixepoch()),
('v445', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'potato_prominence', 2.0, unixepoch()),
('v446', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'novelty', 1.5, unixepoch()),
('v447', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'elegance', -4.0, unixepoch()),
('v448', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'customizability', -1.0, unixepoch()),

-- Clapshot (8edd9660-f8ba-4fd2-bcda-5b516ce592fc)
('v449', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'crispiness', -3.5, unixepoch()),
('v450', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'richness', 2.0, unixepoch()),
('v451', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'flavor_complexity', 0.0, unixepoch()),
('v452', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'heartiness', 2.5, unixepoch()),
('v453', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'potato_prominence', 4.0, unixepoch()),
('v454', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'novelty', 1.5, unixepoch()),
('v455', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'elegance', -1.0, unixepoch()),
('v456', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'customizability', -0.5, unixepoch()),

-- Coddle (275d7111-b716-4c3c-9318-1eacdd9b726d)
('v457', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'crispiness', -3.5, unixepoch()),
('v458', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'richness', 2.5, unixepoch()),
('v459', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'flavor_complexity', 0.5, unixepoch()),
('v460', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'heartiness', 4.0, unixepoch()),
('v461', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'potato_prominence', 2.5, unixepoch()),
('v462', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'novelty', 1.5, unixepoch()),
('v463', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'elegance', -2.0, unixepoch()),
('v464', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'customizability', -1.5, unixepoch()),

-- Cottage pie (822148f1-54d4-41f3-9407-8d1d37d6bc0f)
('v465', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'crispiness', -2.0, unixepoch()),
('v466', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'richness', 3.0, unixepoch()),
('v467', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'flavor_complexity', 1.5, unixepoch()),
('v468', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'heartiness', 5.0, unixepoch()),
('v469', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'potato_prominence', 3.0, unixepoch()),
('v470', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'novelty', -2.0, unixepoch()),
('v471', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'elegance', -0.5, unixepoch()),
('v472', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'customizability', 0.0, unixepoch()),

-- Crisp sandwich (60883922-05ae-466e-bdb9-91006244105c)
('v473', '60883922-05ae-466e-bdb9-91006244105c', 'crispiness', 4.5, unixepoch()),
('v474', '60883922-05ae-466e-bdb9-91006244105c', 'richness', 0.5, unixepoch()),
('v475', '60883922-05ae-466e-bdb9-91006244105c', 'flavor_complexity', -1.5, unixepoch()),
('v476', '60883922-05ae-466e-bdb9-91006244105c', 'heartiness', -2.5, unixepoch()),
('v477', '60883922-05ae-466e-bdb9-91006244105c', 'potato_prominence', 2.0, unixepoch()),
('v478', '60883922-05ae-466e-bdb9-91006244105c', 'novelty', 1.0, unixepoch()),
('v479', '60883922-05ae-466e-bdb9-91006244105c', 'elegance', -4.5, unixepoch()),
('v480', '60883922-05ae-466e-bdb9-91006244105c', 'customizability', 2.0, unixepoch()),

-- Crocchè (70e6a1ef-e59f-470b-9a8b-8f825b608b19)
('v481', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'crispiness', 3.0, unixepoch()),
('v482', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'richness', 2.0, unixepoch()),
('v483', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'flavor_complexity', -0.5, unixepoch()),
('v484', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'heartiness', 0.0, unixepoch()),
('v485', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'potato_prominence', 4.0, unixepoch()),
('v486', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'novelty', 1.5, unixepoch()),
('v487', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'elegance', -1.5, unixepoch()),
('v488', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'customizability', -1.0, unixepoch()),

-- Dabeli (8b584a3e-37ca-4f3d-af8f-89014a53c581)
('v489', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'crispiness', 1.0, unixepoch()),
('v490', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'richness', 1.0, unixepoch()),
('v491', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'flavor_complexity', 2.5, unixepoch()),
('v492', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'heartiness', 1.0, unixepoch()),
('v493', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'potato_prominence', 3.5, unixepoch()),
('v494', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'novelty', 2.0, unixepoch()),
('v495', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'elegance', -3.0, unixepoch()),
('v496', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'customizability', -1.0, unixepoch()),

-- Disco fries (cf2fc462-5619-43c0-9916-fa3cafb216f3)
('v497', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'crispiness', 3.0, unixepoch()),
('v498', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'richness', 3.0, unixepoch()),
('v499', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'flavor_complexity', -0.5, unixepoch()),
('v500', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'heartiness', 2.0, unixepoch()),
('v501', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'potato_prominence', 2.5, unixepoch()),
('v502', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'novelty', 0.0, unixepoch()),
('v503', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'elegance', -3.5, unixepoch()),
('v504', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'customizability', 0.5, unixepoch()),

-- Duchess potatoes (8dd02f58-92de-48de-b5ff-a513e1126fc5)
('v505', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'crispiness', 1.5, unixepoch()),
('v506', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'richness', 3.5, unixepoch()),
('v507', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'flavor_complexity', 0.0, unixepoch()),
('v508', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'heartiness', 2.0, unixepoch()),
('v509', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'potato_prominence', 5.0, unixepoch()),
('v510', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'novelty', 0.5, unixepoch()),
('v511', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'elegance', 3.0, unixepoch()),
('v512', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'customizability', -2.5, unixepoch()),

-- Dum aloo (8171ea87-7217-4d34-b9ce-338de7e25db4)
('v513', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'crispiness', 1.5, unixepoch()),
('v514', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'richness', 1.5, unixepoch()),
('v515', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'flavor_complexity', 3.5, unixepoch()),
('v516', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'heartiness', 2.5, unixepoch()),
('v517', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'potato_prominence', 5.0, unixepoch()),
('v518', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'novelty', 0.5, unixepoch()),
('v519', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'elegance', 0.5, unixepoch()),
('v520', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'customizability', -1.5, unixepoch()),

-- Far far (848a2f87-41f6-46b1-9268-71cff8f31212)
('v521', '848a2f87-41f6-46b1-9268-71cff8f31212', 'crispiness', 4.5, unixepoch()),
('v522', '848a2f87-41f6-46b1-9268-71cff8f31212', 'richness', 0.5, unixepoch()),
('v523', '848a2f87-41f6-46b1-9268-71cff8f31212', 'flavor_complexity', 0.5, unixepoch()),
('v524', '848a2f87-41f6-46b1-9268-71cff8f31212', 'heartiness', -4.0, unixepoch()),
('v525', '848a2f87-41f6-46b1-9268-71cff8f31212', 'potato_prominence', 1.5, unixepoch()),
('v526', '848a2f87-41f6-46b1-9268-71cff8f31212', 'novelty', 3.5, unixepoch()),
('v527', '848a2f87-41f6-46b1-9268-71cff8f31212', 'elegance', -2.5, unixepoch()),
('v528', '848a2f87-41f6-46b1-9268-71cff8f31212', 'customizability', -2.0, unixepoch()),

-- Fondant potatoes (9b31b3c9-9237-472c-998a-b4e4c00e71be)
('v529', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'crispiness', 0.5, unixepoch()),
('v530', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'richness', 3.5, unixepoch()),
('v531', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'flavor_complexity', 0.5, unixepoch()),
('v532', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'heartiness', 2.5, unixepoch()),
('v533', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'potato_prominence', 5.0, unixepoch()),
('v534', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'novelty', 1.0, unixepoch()),
('v535', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'elegance', 4.0, unixepoch()),
('v536', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'customizability', -2.5, unixepoch()),

-- Gamja ongsimi (8db5f070-0889-4a13-95ff-a72938efcae9)
('v537', '8db5f070-0889-4a13-95ff-a72938efcae9', 'crispiness', -4.0, unixepoch()),
('v538', '8db5f070-0889-4a13-95ff-a72938efcae9', 'richness', 1.0, unixepoch()),
('v539', '8db5f070-0889-4a13-95ff-a72938efcae9', 'flavor_complexity', 1.0, unixepoch()),
('v540', '8db5f070-0889-4a13-95ff-a72938efcae9', 'heartiness', 3.0, unixepoch()),
('v541', '8db5f070-0889-4a13-95ff-a72938efcae9', 'potato_prominence', 4.0, unixepoch()),
('v542', '8db5f070-0889-4a13-95ff-a72938efcae9', 'novelty', 4.5, unixepoch()),
('v543', '8db5f070-0889-4a13-95ff-a72938efcae9', 'elegance', 0.5, unixepoch()),
('v544', '8db5f070-0889-4a13-95ff-a72938efcae9', 'customizability', -2.0, unixepoch()),

-- Halal snack pack (5a83e62d-0795-4944-9fa4-35996d36bdeb)
('v545', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'crispiness', 3.5, unixepoch()),
('v546', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'richness', 3.0, unixepoch()),
('v547', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'flavor_complexity', 1.5, unixepoch()),
('v548', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'heartiness', 4.0, unixepoch()),
('v549', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'potato_prominence', 2.0, unixepoch()),
('v550', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'novelty', 0.5, unixepoch()),
('v551', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'elegance', -4.0, unixepoch()),
('v552', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'customizability', 0.0, unixepoch()),

-- Hasselback Potatoes (a7450913-aba9-422c-84fa-64bc1f3a24b0)
('v553', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'crispiness', 2.5, unixepoch()),
('v554', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'richness', 2.0, unixepoch()),
('v555', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'flavor_complexity', 0.0, unixepoch()),
('v556', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'heartiness', 2.5, unixepoch()),
('v557', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'potato_prominence', 5.0, unixepoch()),
('v558', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'novelty', -1.0, unixepoch()),
('v559', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'elegance', 1.5, unixepoch()),
('v560', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'customizability', 1.0, unixepoch()),

-- Home fries (15732175-feb8-4a06-afbe-62dc3c82185e)
('v561', '15732175-feb8-4a06-afbe-62dc3c82185e', 'crispiness', 2.5, unixepoch()),
('v562', '15732175-feb8-4a06-afbe-62dc3c82185e', 'richness', 1.5, unixepoch()),
('v563', '15732175-feb8-4a06-afbe-62dc3c82185e', 'flavor_complexity', -1.0, unixepoch()),
('v564', '15732175-feb8-4a06-afbe-62dc3c82185e', 'heartiness', 1.0, unixepoch()),
('v565', '15732175-feb8-4a06-afbe-62dc3c82185e', 'potato_prominence', 4.5, unixepoch()),
('v566', '15732175-feb8-4a06-afbe-62dc3c82185e', 'novelty', -3.0, unixepoch()),
('v567', '15732175-feb8-4a06-afbe-62dc3c82185e', 'elegance', -3.0, unixepoch()),
('v568', '15732175-feb8-4a06-afbe-62dc3c82185e', 'customizability', 0.5, unixepoch()),

-- Knödel (864d1450-4f9a-4155-9c91-95d43f70b313)
('v569', '864d1450-4f9a-4155-9c91-95d43f70b313', 'crispiness', -3.5, unixepoch()),
('v570', '864d1450-4f9a-4155-9c91-95d43f70b313', 'richness', 2.0, unixepoch()),
('v571', '864d1450-4f9a-4155-9c91-95d43f70b313', 'flavor_complexity', -0.5, unixepoch()),
('v572', '864d1450-4f9a-4155-9c91-95d43f70b313', 'heartiness', 2.5, unixepoch()),
('v573', '864d1450-4f9a-4155-9c91-95d43f70b313', 'potato_prominence', 4.0, unixepoch()),
('v574', '864d1450-4f9a-4155-9c91-95d43f70b313', 'novelty', 1.0, unixepoch()),
('v575', '864d1450-4f9a-4155-9c91-95d43f70b313', 'elegance', 0.0, unixepoch()),
('v576', '864d1450-4f9a-4155-9c91-95d43f70b313', 'customizability', -1.5, unixepoch()),

-- Kopytka (96545002-0d3c-4739-9074-a5d630bf9e6a)
('v577', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'crispiness', -3.5, unixepoch()),
('v578', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'richness', 1.5, unixepoch()),
('v579', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'flavor_complexity', -1.0, unixepoch()),
('v580', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'heartiness', 2.5, unixepoch()),
('v581', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'potato_prominence', 4.5, unixepoch()),
('v582', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'novelty', 1.5, unixepoch()),
('v583', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'elegance', -0.5, unixepoch()),
('v584', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'customizability', -1.5, unixepoch()),

-- Korokke (fe63cd3e-2051-4881-9a4b-81eb0546800c)
('v585', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'crispiness', 3.5, unixepoch()),
('v586', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'richness', 2.0, unixepoch()),
('v587', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'flavor_complexity', 0.5, unixepoch()),
('v588', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'heartiness', 0.5, unixepoch()),
('v589', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'potato_prominence', 3.0, unixepoch()),
('v590', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'novelty', 0.0, unixepoch()),
('v591', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'elegance', -1.0, unixepoch()),
('v592', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'customizability', -1.0, unixepoch()),

-- Kroppkaka (ab08c0b6-083c-4653-a6d1-7b7debc48256)
('v593', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'crispiness', -3.0, unixepoch()),
('v594', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'richness', 2.5, unixepoch()),
('v595', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'flavor_complexity', 0.0, unixepoch()),
('v596', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'heartiness', 4.0, unixepoch()),
('v597', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'potato_prominence', 4.0, unixepoch()),
('v598', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'novelty', 4.0, unixepoch()),
('v599', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'elegance', -1.0, unixepoch()),
('v600', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'customizability', -2.5, unixepoch()),

-- Kugel (8756548c-c91e-4548-89de-33842719228f)
('v601', '8756548c-c91e-4548-89de-33842719228f', 'crispiness', -3.0, unixepoch()),
('v602', '8756548c-c91e-4548-89de-33842719228f', 'richness', 3.0, unixepoch()),
('v603', '8756548c-c91e-4548-89de-33842719228f', 'flavor_complexity', -0.5, unixepoch()),
('v604', '8756548c-c91e-4548-89de-33842719228f', 'heartiness', 3.0, unixepoch()),
('v605', '8756548c-c91e-4548-89de-33842719228f', 'potato_prominence', 3.5, unixepoch()),
('v606', '8756548c-c91e-4548-89de-33842719228f', 'novelty', 0.0, unixepoch()),
('v607', '8756548c-c91e-4548-89de-33842719228f', 'elegance', -1.0, unixepoch()),
('v608', '8756548c-c91e-4548-89de-33842719228f', 'customizability', -1.0, unixepoch()),

-- Meat and potato pie (98f0a34c-ea71-4a65-b35e-67b3768e8c7e)
('v609', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'crispiness', -2.0, unixepoch()),
('v610', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'richness', 2.5, unixepoch()),
('v611', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'flavor_complexity', 0.5, unixepoch()),
('v612', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'heartiness', 4.5, unixepoch()),
('v613', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'potato_prominence', 2.5, unixepoch()),
('v614', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'novelty', -1.0, unixepoch()),
('v615', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'elegance', -2.0, unixepoch()),
('v616', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'customizability', -1.0, unixepoch()),

-- Nikujaga (b7894ef6-354b-4a37-a73a-a9a14c0efb50)
('v617', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'crispiness', -3.5, unixepoch()),
('v618', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'richness', 1.5, unixepoch()),
('v619', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'flavor_complexity', 2.0, unixepoch()),
('v620', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'heartiness', 4.0, unixepoch()),
('v621', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'potato_prominence', 3.5, unixepoch()),
('v622', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'novelty', 1.5, unixepoch()),
('v623', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'elegance', -1.0, unixepoch()),
('v624', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'customizability', -1.0, unixepoch()),

-- Nilaga (78063773-32b5-4ed9-9273-bedec6114f6b)
('v625', '78063773-32b5-4ed9-9273-bedec6114f6b', 'crispiness', -4.0, unixepoch()),
('v626', '78063773-32b5-4ed9-9273-bedec6114f6b', 'richness', 1.5, unixepoch()),
('v627', '78063773-32b5-4ed9-9273-bedec6114f6b', 'flavor_complexity', 1.0, unixepoch()),
('v628', '78063773-32b5-4ed9-9273-bedec6114f6b', 'heartiness', 4.5, unixepoch()),
('v629', '78063773-32b5-4ed9-9273-bedec6114f6b', 'potato_prominence', 3.0, unixepoch()),
('v630', '78063773-32b5-4ed9-9273-bedec6114f6b', 'novelty', 2.5, unixepoch()),
('v631', '78063773-32b5-4ed9-9273-bedec6114f6b', 'elegance', -1.5, unixepoch()),
('v632', '78063773-32b5-4ed9-9273-bedec6114f6b', 'customizability', -1.0, unixepoch()),

-- Okroshka (64700da3-9866-44da-8f95-738f5a8afb1d)
('v633', '64700da3-9866-44da-8f95-738f5a8afb1d', 'crispiness', -4.0, unixepoch()),
('v634', '64700da3-9866-44da-8f95-738f5a8afb1d', 'richness', 1.0, unixepoch()),
('v635', '64700da3-9866-44da-8f95-738f5a8afb1d', 'flavor_complexity', 1.5, unixepoch()),
('v636', '64700da3-9866-44da-8f95-738f5a8afb1d', 'heartiness', 2.5, unixepoch()),
('v637', '64700da3-9866-44da-8f95-738f5a8afb1d', 'potato_prominence', 2.5, unixepoch()),
('v638', '64700da3-9866-44da-8f95-738f5a8afb1d', 'novelty', 3.0, unixepoch()),
('v639', '64700da3-9866-44da-8f95-738f5a8afb1d', 'elegance', -1.5, unixepoch()),
('v640', '64700da3-9866-44da-8f95-738f5a8afb1d', 'customizability', -1.0, unixepoch()),

-- Olivier salad (06a7831b-bce7-40f0-921c-14774c00dbfb)
('v641', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'crispiness', -3.0, unixepoch()),
('v642', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'richness', 1.5, unixepoch()),
('v643', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'flavor_complexity', 1.0, unixepoch()),
('v644', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'heartiness', 2.0, unixepoch()),
('v645', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'potato_prominence', 2.5, unixepoch()),
('v646', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'novelty', -1.0, unixepoch()),
('v647', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'elegance', -1.5, unixepoch()),
('v648', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'customizability', -1.5, unixepoch()),

-- Papa rellena (ee44f68c-0446-45fa-9471-9e6041646e86)
('v649', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'crispiness', 3.5, unixepoch()),
('v650', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'richness', 2.5, unixepoch()),
('v651', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'flavor_complexity', 1.5, unixepoch()),
('v652', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'heartiness', 2.0, unixepoch()),
('v653', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'potato_prominence', 4.0, unixepoch()),
('v654', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'novelty', 1.5, unixepoch()),
('v655', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'elegance', -2.0, unixepoch()),
('v656', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'customizability', -1.5, unixepoch()),

-- Pickert (bd3f208c-0432-4124-96b5-0c303e50009b)
('v657', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'crispiness', 1.5, unixepoch()),
('v658', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'richness', 1.5, unixepoch()),
('v659', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'flavor_complexity', -1.0, unixepoch()),
('v660', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'heartiness', 1.5, unixepoch()),
('v661', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'potato_prominence', 4.5, unixepoch()),
('v662', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'novelty', 3.0, unixepoch()),
('v663', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'elegance', -2.0, unixepoch()),
('v664', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'customizability', -1.0, unixepoch()),

-- Pommes dauphine (730fa480-f456-46d7-9203-4dc5a913dce2)
('v665', '730fa480-f456-46d7-9203-4dc5a913dce2', 'crispiness', 4.0, unixepoch()),
('v666', '730fa480-f456-46d7-9203-4dc5a913dce2', 'richness', 3.0, unixepoch()),
('v667', '730fa480-f456-46d7-9203-4dc5a913dce2', 'flavor_complexity', -0.5, unixepoch()),
('v668', '730fa480-f456-46d7-9203-4dc5a913dce2', 'heartiness', 0.0, unixepoch()),
('v669', '730fa480-f456-46d7-9203-4dc5a913dce2', 'potato_prominence', 3.5, unixepoch()),
('v670', '730fa480-f456-46d7-9203-4dc5a913dce2', 'novelty', 0.5, unixepoch()),
('v671', '730fa480-f456-46d7-9203-4dc5a913dce2', 'elegance', 1.5, unixepoch()),
('v672', '730fa480-f456-46d7-9203-4dc5a913dce2', 'customizability', -2.0, unixepoch()),

-- Pommes soufflées (db9533ba-36e5-4894-8c97-f91ac02a87c7)
('v673', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'crispiness', 5.0, unixepoch()),
('v674', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'richness', 1.5, unixepoch()),
('v675', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'flavor_complexity', -1.5, unixepoch()),
('v676', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'heartiness', -2.0, unixepoch()),
('v677', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'potato_prominence', 5.0, unixepoch()),
('v678', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'novelty', 1.5, unixepoch()),
('v679', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'elegance', 2.0, unixepoch()),
('v680', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'customizability', -3.0, unixepoch()),

-- Potato bread (807433ce-98aa-416c-a6d0-a130caa1c0fd)
('v681', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'crispiness', 0.5, unixepoch()),
('v682', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'richness', 0.5, unixepoch()),
('v683', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'flavor_complexity', -1.5, unixepoch()),
('v684', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'heartiness', -0.5, unixepoch()),
('v685', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'potato_prominence', 2.5, unixepoch()),
('v686', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'novelty', -1.5, unixepoch()),
('v687', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'elegance', -1.5, unixepoch()),
('v688', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'customizability', 0.5, unixepoch()),

-- Potato candy (07e057e6-7d58-4010-bc4a-1a6150a93012)
('v689', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'crispiness', -2.5, unixepoch()),
('v690', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'richness', 3.5, unixepoch()),
('v691', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'flavor_complexity', -1.0, unixepoch()),
('v692', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'heartiness', -4.0, unixepoch()),
('v693', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'potato_prominence', 2.0, unixepoch()),
('v694', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'novelty', 3.5, unixepoch()),
('v695', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'elegance', -1.0, unixepoch()),
('v696', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'customizability', -2.5, unixepoch()),

-- Potato doughnut (b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b)
('v697', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'crispiness', 1.0, unixepoch()),
('v698', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'richness', 3.0, unixepoch()),
('v699', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'flavor_complexity', -1.0, unixepoch()),
('v700', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'heartiness', -3.0, unixepoch()),
('v701', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'potato_prominence', 2.5, unixepoch()),
('v702', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'novelty', 2.0, unixepoch()),
('v703', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'elegance', -2.5, unixepoch()),
('v704', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'customizability', -1.5, unixepoch()),

-- Potato filling (d5ede357-0627-464a-8ccc-158aed7a23d3)
('v705', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'crispiness', -2.5, unixepoch()),
('v706', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'richness', 2.0, unixepoch()),
('v707', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'flavor_complexity', -0.5, unixepoch()),
('v708', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'heartiness', 2.0, unixepoch()),
('v709', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'potato_prominence', 4.0, unixepoch()),
('v710', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'novelty', 1.5, unixepoch()),
('v711', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'elegance', -2.0, unixepoch()),
('v712', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'customizability', -1.0, unixepoch()),

-- Potato scone (e660f55e-1f42-4692-ae3b-7017622fa40f)
('v713', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'crispiness', 0.5, unixepoch()),
('v714', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'richness', 1.5, unixepoch()),
('v715', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'flavor_complexity', -1.5, unixepoch()),
('v716', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'heartiness', 0.0, unixepoch()),
('v717', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'potato_prominence', 4.5, unixepoch()),
('v718', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'novelty', 1.0, unixepoch()),
('v719', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'elegance', -2.5, unixepoch()),
('v720', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'customizability', 0.0, unixepoch()),

-- Potato waffle (d8abbffc-393e-4c06-b257-32ddccc7edee)
('v721', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'crispiness', 3.0, unixepoch()),
('v722', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'richness', 1.5, unixepoch()),
('v723', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'flavor_complexity', -1.5, unixepoch()),
('v724', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'heartiness', -1.0, unixepoch()),
('v725', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'potato_prominence', 4.0, unixepoch()),
('v726', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'novelty', 0.5, unixepoch()),
('v727', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'elegance', -3.0, unixepoch()),
('v728', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'customizability', -1.0, unixepoch()),

-- Poutine (8fcb5b3a-0ae0-438b-85e6-2ceec36b070f)
('v729', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'crispiness', 3.5, unixepoch()),
('v730', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'richness', 3.5, unixepoch()),
('v731', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'flavor_complexity', 0.5, unixepoch()),
('v732', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'heartiness', 3.0, unixepoch()),
('v733', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'potato_prominence', 3.0, unixepoch()),
('v734', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'novelty', -1.5, unixepoch()),
('v735', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'elegance', -3.5, unixepoch()),
('v736', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'customizability', 0.5, unixepoch()),

-- Rumbledethumps (2e6b4457-6c93-4323-a91a-ff8266b30b69)
('v737', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'crispiness', -1.5, unixepoch()),
('v738', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'richness', 2.0, unixepoch()),
('v739', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'flavor_complexity', -0.5, unixepoch()),
('v740', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'heartiness', 2.5, unixepoch()),
('v741', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'potato_prominence', 4.0, unixepoch()),
('v742', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'novelty', 1.0, unixepoch()),
('v743', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'elegance', -2.0, unixepoch()),
('v744', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'customizability', -0.5, unixepoch()),

-- Salchipapa (faa61fbe-7bf1-495e-a4bc-d00c38bba754)
('v745', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'crispiness', 3.5, unixepoch()),
('v746', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'richness', 2.0, unixepoch()),
('v747', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'flavor_complexity', -0.5, unixepoch()),
('v748', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'heartiness', 2.5, unixepoch()),
('v749', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'potato_prominence', 2.5, unixepoch()),
('v750', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'novelty', 0.5, unixepoch()),
('v751', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'elegance', -4.0, unixepoch()),
('v752', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'customizability', -0.5, unixepoch()),

-- Salt potatoes (bee560c0-5e89-4467-983e-4a82c143dbf7)
('v753', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'crispiness', -1.5, unixepoch()),
('v754', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'richness', -1.5, unixepoch()),
('v755', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'flavor_complexity', -2.0, unixepoch()),
('v756', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'heartiness', 1.0, unixepoch()),
('v757', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'potato_prominence', 5.0, unixepoch()),
('v758', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'novelty', 0.5, unixepoch()),
('v759', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'elegance', -1.5, unixepoch()),
('v760', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'customizability', -2.5, unixepoch()),

-- Samosa (176f86ec-6966-43a2-ba73-f872248d7a7c)
('v761', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'crispiness', 3.5, unixepoch()),
('v762', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'richness', 1.0, unixepoch()),
('v763', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'flavor_complexity', 2.0, unixepoch()),
('v764', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'heartiness', 0.5, unixepoch()),
('v765', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'potato_prominence', 2.5, unixepoch()),
('v766', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'novelty', -2.0, unixepoch()),
('v767', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'elegance', -2.0, unixepoch()),
('v768', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'customizability', -2.0, unixepoch()),

-- Schupfnudel (8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb)
('v769', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'crispiness', -2.0, unixepoch()),
('v770', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'richness', 1.5, unixepoch()),
('v771', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'flavor_complexity', -0.5, unixepoch()),
('v772', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'heartiness', 2.0, unixepoch()),
('v773', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'potato_prominence', 4.0, unixepoch()),
('v774', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'novelty', 1.5, unixepoch()),
('v775', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'elegance', -0.5, unixepoch()),
('v776', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'customizability', -1.0, unixepoch()),

-- Silesian dumplings (6b3159a2-eaf7-4582-8926-fc96ded4d716)
('v777', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'crispiness', -3.5, unixepoch()),
('v778', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'richness', 1.5, unixepoch()),
('v779', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'flavor_complexity', -1.0, unixepoch()),
('v780', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'heartiness', 2.5, unixepoch()),
('v781', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'potato_prominence', 4.5, unixepoch()),
('v782', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'novelty', 2.0, unixepoch()),
('v783', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'elegance', -0.5, unixepoch()),
('v784', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'customizability', -2.0, unixepoch()),

-- Spice bag (cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7)
('v785', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'crispiness', 3.5, unixepoch()),
('v786', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'richness', 2.0, unixepoch()),
('v787', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'flavor_complexity', 2.0, unixepoch()),
('v788', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'heartiness', 1.5, unixepoch()),
('v789', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'potato_prominence', 2.5, unixepoch()),
('v790', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'novelty', 1.5, unixepoch()),
('v791', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'elegance', -4.0, unixepoch()),
('v792', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'customizability', -1.0, unixepoch()),

-- Steak frites (8fd9f188-564d-462d-8382-ca426986ae96)
('v793', '8fd9f188-564d-462d-8382-ca426986ae96', 'crispiness', 3.5, unixepoch()),
('v794', '8fd9f188-564d-462d-8382-ca426986ae96', 'richness', 2.0, unixepoch()),
('v795', '8fd9f188-564d-462d-8382-ca426986ae96', 'flavor_complexity', -1.0, unixepoch()),
('v796', '8fd9f188-564d-462d-8382-ca426986ae96', 'heartiness', 4.0, unixepoch()),
('v797', '8fd9f188-564d-462d-8382-ca426986ae96', 'potato_prominence', 2.0, unixepoch()),
('v798', '8fd9f188-564d-462d-8382-ca426986ae96', 'novelty', -2.5, unixepoch()),
('v799', '8fd9f188-564d-462d-8382-ca426986ae96', 'elegance', 1.0, unixepoch()),
('v800', '8fd9f188-564d-462d-8382-ca426986ae96', 'customizability', -1.0, unixepoch()),

-- Sweetened potato casserole (99de5a25-6e0f-4386-aecd-d184cc88ff7b)
('v801', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'crispiness', -3.0, unixepoch()),
('v802', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'richness', 3.0, unixepoch()),
('v803', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'flavor_complexity', -1.0, unixepoch()),
('v804', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'heartiness', 3.0, unixepoch()),
('v805', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'potato_prominence', 3.5, unixepoch()),
('v806', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'novelty', 1.5, unixepoch()),
('v807', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'elegance', -1.5, unixepoch()),
('v808', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'customizability', -2.0, unixepoch()),

-- Tombet (439bcad0-072b-49fb-9ccc-41ba20f91c85)
('v809', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'crispiness', 0.5, unixepoch()),
('v810', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'richness', 1.5, unixepoch()),
('v811', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'flavor_complexity', 1.5, unixepoch()),
('v812', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'heartiness', 2.5, unixepoch()),
('v813', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'potato_prominence', 4.0, unixepoch()),
('v814', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'novelty', 3.0, unixepoch()),
('v815', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'elegance', 0.5, unixepoch()),
('v816', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'customizability', -2.0, unixepoch()),

-- Tornado potato (d74cf91f-e373-48bc-a214-5b4bb31d76cf)
('v817', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'crispiness', 4.5, unixepoch()),
('v818', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'richness', 0.5, unixepoch()),
('v819', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'flavor_complexity', -1.0, unixepoch()),
('v820', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'heartiness', -2.0, unixepoch()),
('v821', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'potato_prominence', 5.0, unixepoch()),
('v822', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'novelty', 1.5, unixepoch()),
('v823', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'elegance', -2.5, unixepoch()),
('v824', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'customizability', -2.5, unixepoch());
