-- Migration: Seed criteria votes for all dishes
-- Created: 2026-04-15
-- Votes for potato dishes as generated by Claude Sonnet 4.6

INSERT INTO dish_criteria_votes (id, dish_id, criterion_id, score, created_at) VALUES
-- Mashed Potatoes (a1b2c3d4-e5f6-7890-abcd-ef1234567890)
('c001', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'crispiness', -4.5, unixepoch()),
('c002', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'richness', 3.0, unixepoch()),
('c003', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'flavor_complexity', -2.5, unixepoch()),
('c004', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'heartiness', 2.0, unixepoch()),
('c005', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'potato_prominence', 5.0, unixepoch()),
('c006', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'novelty', -4.5, unixepoch()),
('c007', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'elegance', -1.0, unixepoch()),
('c008', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'customizability', 3.0, unixepoch()),

-- French Fries (b2c3d4e5-f6a7-8901-bcde-f12345678901)
('c009', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'crispiness', 5.0, unixepoch()),
('c010', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'richness', 1.5, unixepoch()),
('c011', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'flavor_complexity', -2.0, unixepoch()),
('c012', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'heartiness', -1.5, unixepoch()),
('c013', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'potato_prominence', 5.0, unixepoch()),
('c014', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'novelty', -5.0, unixepoch()),
('c015', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'elegance', -3.5, unixepoch()),
('c016', 'b2c3d4e5-f6a7-8901-bcde-f12345678901', 'customizability', 4.0, unixepoch()),

-- Baked Potato (c3d4e5f6-a7b8-9012-cdef-123456789012)
('c017', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'crispiness', -0.5, unixepoch()),
('c018', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'richness', -1.0, unixepoch()),
('c019', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'flavor_complexity', -3.0, unixepoch()),
('c020', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'heartiness', 2.0, unixepoch()),
('c021', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'potato_prominence', 5.0, unixepoch()),
('c022', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'novelty', -4.5, unixepoch()),
('c023', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'elegance', -1.5, unixepoch()),
('c024', 'c3d4e5f6-a7b8-9012-cdef-123456789012', 'customizability', 5.0, unixepoch()),

-- Potato Soup (d4e5f6a7-b8c9-0123-def1-234567890123)
('c025', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'crispiness', -4.5, unixepoch()),
('c026', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'richness', 2.5, unixepoch()),
('c027', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'flavor_complexity', -1.0, unixepoch()),
('c028', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'heartiness', 3.0, unixepoch()),
('c029', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'potato_prominence', 4.0, unixepoch()),
('c030', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'novelty', -3.5, unixepoch()),
('c031', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'elegance', 0.0, unixepoch()),
('c032', 'd4e5f6a7-b8c9-0123-def1-234567890123', 'customizability', 1.5, unixepoch()),

-- Potato Salad (e5f6a7b8-c9d0-1234-ef12-345678901234)
('c033', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'crispiness', -3.0, unixepoch()),
('c034', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'richness', 1.0, unixepoch()),
('c035', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'flavor_complexity', 0.0, unixepoch()),
('c036', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'heartiness', -1.0, unixepoch()),
('c037', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'potato_prominence', 4.5, unixepoch()),
('c038', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'novelty', -3.5, unixepoch()),
('c039', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'elegance', -2.0, unixepoch()),
('c040', 'e5f6a7b8-c9d0-1234-ef12-345678901234', 'customizability', 2.5, unixepoch()),

-- Hash Browns (f6a7b8c9-d0e1-2345-f123-456789012345)
('c041', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'crispiness', 4.0, unixepoch()),
('c042', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'richness', 1.5, unixepoch()),
('c043', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'flavor_complexity', -2.5, unixepoch()),
('c044', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'heartiness', -1.0, unixepoch()),
('c045', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'potato_prominence', 5.0, unixepoch()),
('c046', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'novelty', -3.5, unixepoch()),
('c047', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'elegance', -3.5, unixepoch()),
('c048', 'f6a7b8c9-d0e1-2345-f123-456789012345', 'customizability', 0.5, unixepoch()),

-- Potato Gratin (a7b8c9d0-e1f2-3456-1234-567890123456)
('c049', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'crispiness', 1.0, unixepoch()),
('c050', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'richness', 4.5, unixepoch()),
('c051', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'flavor_complexity', 1.0, unixepoch()),
('c052', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'heartiness', 3.5, unixepoch()),
('c053', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'potato_prominence', 4.5, unixepoch()),
('c054', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'novelty', -2.0, unixepoch()),
('c055', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'elegance', 2.0, unixepoch()),
('c056', 'a7b8c9d0-e1f2-3456-1234-567890123456', 'customizability', -1.0, unixepoch()),

-- Shepherd's Pie (b8c9d0e1-f2a3-4567-2345-678901234567)
('c057', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'crispiness', -1.5, unixepoch()),
('c058', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'richness', 3.0, unixepoch()),
('c059', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'flavor_complexity', 2.0, unixepoch()),
('c060', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'heartiness', 5.0, unixepoch()),
('c061', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'potato_prominence', 3.0, unixepoch()),
('c062', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'novelty', -2.5, unixepoch()),
('c063', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'elegance', 0.5, unixepoch()),
('c064', 'b8c9d0e1-f2a3-4567-2345-678901234567', 'customizability', 1.0, unixepoch()),

-- Potato Gnocchi (c9d0e1f2-a3b4-5678-3456-789012345678)
('c065', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'crispiness', -3.0, unixepoch()),
('c066', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'richness', 2.0, unixepoch()),
('c067', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'flavor_complexity', 1.0, unixepoch()),
('c068', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'heartiness', 2.5, unixepoch()),
('c069', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'potato_prominence', 3.5, unixepoch()),
('c070', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'novelty', -1.5, unixepoch()),
('c071', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'elegance', 1.5, unixepoch()),
('c072', 'c9d0e1f2-a3b4-5678-3456-789012345678', 'customizability', 2.0, unixepoch()),

-- Potato Latkes (d0e1f2a3-b4c5-6789-4567-890123456789)
('c073', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'crispiness', 4.0, unixepoch()),
('c074', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'richness', 2.0, unixepoch()),
('c075', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'flavor_complexity', 0.0, unixepoch()),
('c076', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'heartiness', 0.0, unixepoch()),
('c077', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'potato_prominence', 4.5, unixepoch()),
('c078', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'novelty', -1.0, unixepoch()),
('c079', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'elegance', -1.0, unixepoch()),
('c080', 'd0e1f2a3-b4c5-6789-4567-890123456789', 'customizability', 2.0, unixepoch()),

-- Potato Wedges (a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e)
('c081', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'crispiness', 3.0, unixepoch()),
('c082', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'richness', 0.5, unixepoch()),
('c083', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'flavor_complexity', -0.5, unixepoch()),
('c084', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'heartiness', 0.0, unixepoch()),
('c085', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'potato_prominence', 5.0, unixepoch()),
('c086', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'novelty', -4.0, unixepoch()),
('c087', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'elegance', -3.0, unixepoch()),
('c088', 'a7c3e9f1-2b4d-5f8a-9c1e-3d7b5f2a8c6e', 'customizability', 2.0, unixepoch()),

-- Scalloped Potatoes (b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f)
('c089', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'crispiness', -1.0, unixepoch()),
('c090', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'richness', 4.0, unixepoch()),
('c091', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'flavor_complexity', 0.5, unixepoch()),
('c092', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'heartiness', 3.0, unixepoch()),
('c093', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'potato_prominence', 5.0, unixepoch()),
('c094', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'novelty', -2.5, unixepoch()),
('c095', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'elegance', 1.0, unixepoch()),
('c096', 'b8d4f0a2-3c5e-6b9f-0d2f-4e8c6a3b9d7f', 'customizability', -0.5, unixepoch()),

-- Potato Skins (c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a)
('c097', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'crispiness', 4.0, unixepoch()),
('c098', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'richness', 2.5, unixepoch()),
('c099', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'flavor_complexity', 1.0, unixepoch()),
('c100', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'heartiness', 0.0, unixepoch()),
('c101', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'potato_prominence', 3.5, unixepoch()),
('c102', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'novelty', -2.0, unixepoch()),
('c103', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'elegance', -3.0, unixepoch()),
('c104', 'c9e5a1b3-4d6f-7c0a-1e3a-5f9d7b4c0e8a', 'customizability', 4.5, unixepoch()),

-- Tater Tots (d0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b)
('c105', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'crispiness', 4.5, unixepoch()),
('c106', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'richness', 1.5, unixepoch()),
('c107', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'flavor_complexity', -2.5, unixepoch()),
('c108', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'heartiness', -2.0, unixepoch()),
('c109', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'potato_prominence', 4.0, unixepoch()),
('c110', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'novelty', -3.0, unixepoch()),
('c111', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'elegance', -4.5, unixepoch()),
('c112', 'd0f6b2c4-5e7a-8d1b-2f4b-6a0e8c5d1f9b', 'customizability', 1.0, unixepoch()),

-- Potato Chips (e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c)
('c113', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'crispiness', 5.0, unixepoch()),
('c114', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'richness', 0.5, unixepoch()),
('c115', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'flavor_complexity', 0.0, unixepoch()),
('c116', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'heartiness', -4.0, unixepoch()),
('c117', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'potato_prominence', 4.5, unixepoch()),
('c118', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'novelty', -4.5, unixepoch()),
('c119', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'elegance', -3.5, unixepoch()),
('c120', 'e1a7c3d5-6f8b-9e2c-3c5c-7b1f9d6e2a0c', 'customizability', 1.5, unixepoch()),

-- Roasted Potatoes (f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d)
('c121', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'crispiness', 3.5, unixepoch()),
('c122', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'richness', 1.0, unixepoch()),
('c123', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'flavor_complexity', 0.0, unixepoch()),
('c124', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'heartiness', 1.5, unixepoch()),
('c125', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'potato_prominence', 5.0, unixepoch()),
('c126', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'novelty', -3.5, unixepoch()),
('c127', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'elegance', -0.5, unixepoch()),
('c128', 'f2b8d4e6-7a9c-0f3d-4d6d-8c2a0e7f3b1d', 'customizability', 2.0, unixepoch()),

-- Potato Pancakes (a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e)
('c129', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'crispiness', 3.5, unixepoch()),
('c130', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'richness', 1.0, unixepoch()),
('c131', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'flavor_complexity', -0.5, unixepoch()),
('c132', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'heartiness', -0.5, unixepoch()),
('c133', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'potato_prominence', 4.5, unixepoch()),
('c134', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'novelty', -2.0, unixepoch()),
('c135', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'elegance', -1.5, unixepoch()),
('c136', 'a3c9e5f7-8b0d-1a4e-5e7e-9d3b1f8a4c2e', 'customizability', 1.0, unixepoch()),

-- Colcannon (b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f)
('c137', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'crispiness', -4.0, unixepoch()),
('c138', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'richness', 2.5, unixepoch()),
('c139', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'flavor_complexity', 0.5, unixepoch()),
('c140', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'heartiness', 2.5, unixepoch()),
('c141', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'potato_prominence', 4.0, unixepoch()),
('c142', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'novelty', -0.5, unixepoch()),
('c143', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'elegance', -1.0, unixepoch()),
('c144', 'b4d0f6a8-9c1e-2b5f-6f8f-0e4c2a9b5d3f', 'customizability', 0.5, unixepoch()),

-- Boxty (c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a)
('c145', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'crispiness', 2.5, unixepoch()),
('c146', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'richness', 1.0, unixepoch()),
('c147', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'flavor_complexity', -1.0, unixepoch()),
('c148', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'heartiness', 1.0, unixepoch()),
('c149', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'potato_prominence', 5.0, unixepoch()),
('c150', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'novelty', 2.0, unixepoch()),
('c151', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'elegance', -1.0, unixepoch()),
('c152', 'c5e1a7b9-0d2f-3c6a-7a9a-1f5d3b0c6e4a', 'customizability', 1.0, unixepoch()),

-- Potato Croquettes (d6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b)
('c153', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'crispiness', 4.0, unixepoch()),
('c154', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'richness', 2.5, unixepoch()),
('c155', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'flavor_complexity', 0.0, unixepoch()),
('c156', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'heartiness', 0.5, unixepoch()),
('c157', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'potato_prominence', 4.0, unixepoch()),
('c158', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'novelty', -1.0, unixepoch()),
('c159', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'elegance', 0.5, unixepoch()),
('c160', 'd6f2b8c0-1e3a-4d7b-8b0b-2a6e4c1d7f5b', 'customizability', -0.5, unixepoch()),

-- Patatas Bravas (e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c)
('c161', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'crispiness', 3.5, unixepoch()),
('c162', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'richness', 1.5, unixepoch()),
('c163', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'flavor_complexity', 2.5, unixepoch()),
('c164', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'heartiness', 1.0, unixepoch()),
('c165', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'potato_prominence', 4.5, unixepoch()),
('c166', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'novelty', -1.5, unixepoch()),
('c167', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'elegance', -0.5, unixepoch()),
('c168', 'e7a3c9d1-2f4b-5e8c-9c1c-3b7f5d2e8a6c', 'customizability', -1.5, unixepoch()),

-- Potato Curry (f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d)
('c169', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'crispiness', -3.0, unixepoch()),
('c170', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'richness', 2.0, unixepoch()),
('c171', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'flavor_complexity', 3.5, unixepoch()),
('c172', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'heartiness', 3.5, unixepoch()),
('c173', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'potato_prominence', 3.5, unixepoch()),
('c174', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'novelty', -1.0, unixepoch()),
('c175', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'elegance', -1.5, unixepoch()),
('c176', 'f8b4d0e2-3a5c-6f9d-0d2d-4c8a6e3f9b7d', 'customizability', 1.0, unixepoch()),

-- Spanish Tortilla (a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e)
('c177', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'crispiness', -1.5, unixepoch()),
('c178', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'richness', 2.0, unixepoch()),
('c179', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'flavor_complexity', 0.5, unixepoch()),
('c180', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'heartiness', 2.5, unixepoch()),
('c181', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'potato_prominence', 4.0, unixepoch()),
('c182', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'novelty', -1.0, unixepoch()),
('c183', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'elegance', 0.5, unixepoch()),
('c184', 'a9c5e1f3-4b6d-7a0e-1e3e-5d9b7f4a0c8e', 'customizability', -1.5, unixepoch()),

-- Potato Rosti (b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f)
('c185', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'crispiness', 4.0, unixepoch()),
('c186', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'richness', 1.5, unixepoch()),
('c187', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'flavor_complexity', -1.5, unixepoch()),
('c188', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'heartiness', 1.5, unixepoch()),
('c189', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'potato_prominence', 5.0, unixepoch()),
('c190', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'novelty', 0.5, unixepoch()),
('c191', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'elegance', 0.5, unixepoch()),
('c192', 'b0d6f2a4-5c7e-8b1f-2f4f-6e0c8a5b1d9f', 'customizability', -0.5, unixepoch()),

-- Funeral Potatoes (c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c)
('c193', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'crispiness', 1.5, unixepoch()),
('c194', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'richness', 5.0, unixepoch()),
('c195', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'flavor_complexity', 0.5, unixepoch()),
('c196', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'heartiness', 4.0, unixepoch()),
('c197', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'potato_prominence', 3.5, unixepoch()),
('c198', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'novelty', 1.5, unixepoch()),
('c199', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'elegance', -3.0, unixepoch()),
('c200', 'c1e7a3b5-6d8f-9c2a-3a5a-7f1d9b6e2a0c', 'customizability', 0.5, unixepoch()),

-- Potato Leek Soup (d2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d)
('c201', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'crispiness', -5.0, unixepoch()),
('c202', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'richness', 2.5, unixepoch()),
('c203', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'flavor_complexity', 1.0, unixepoch()),
('c204', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'heartiness', 2.5, unixepoch()),
('c205', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'potato_prominence', 3.0, unixepoch()),
('c206', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'novelty', -2.0, unixepoch()),
('c207', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'elegance', 1.5, unixepoch()),
('c208', 'd2f8b4c6-7e9a-0d3b-4b6b-8a2e0c7f3b1d', 'customizability', 0.0, unixepoch()),

-- Pommes Anna (e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e)
('c209', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'crispiness', 2.0, unixepoch()),
('c210', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'richness', 4.0, unixepoch()),
('c211', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'flavor_complexity', -1.5, unixepoch()),
('c212', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'heartiness', 2.0, unixepoch()),
('c213', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'potato_prominence', 5.0, unixepoch()),
('c214', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'novelty', 1.5, unixepoch()),
('c215', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'elegance', 4.0, unixepoch()),
('c216', 'e3a9c5d7-8f0b-1e4c-5c7c-9b3f1d8a4c2e', 'customizability', -3.0, unixepoch()),

-- Potato Pierogi (f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f)
('c217', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'crispiness', -2.0, unixepoch()),
('c218', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'richness', 2.0, unixepoch()),
('c219', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'flavor_complexity', 0.5, unixepoch()),
('c220', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'heartiness', 2.5, unixepoch()),
('c221', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'potato_prominence', 4.0, unixepoch()),
('c222', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'novelty', -0.5, unixepoch()),
('c223', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'elegance', -0.5, unixepoch()),
('c224', 'f4b0d6e8-9a1c-2f5d-6d8d-0c4a2e9b5d3f', 'customizability', -0.5, unixepoch()),

-- Sweet Potato Fries (a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a)
('c225', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'crispiness', 3.5, unixepoch()),
('c226', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'richness', 0.5, unixepoch()),
('c227', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'flavor_complexity', 0.5, unixepoch()),
('c228', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'heartiness', -1.0, unixepoch()),
('c229', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'potato_prominence', 2.5, unixepoch()),
('c230', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'novelty', -2.5, unixepoch()),
('c231', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'elegance', -2.0, unixepoch()),
('c232', 'a5c1e7f9-0b2d-3a6e-7e9e-1d5b3f0c6e4a', 'customizability', 2.0, unixepoch()),

-- Twice Baked Potatoes (b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b)
('c233', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'crispiness', 0.5, unixepoch()),
('c234', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'richness', 3.5, unixepoch()),
('c235', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'flavor_complexity', 1.0, unixepoch()),
('c236', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'heartiness', 3.0, unixepoch()),
('c237', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'potato_prominence', 4.5, unixepoch()),
('c238', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'novelty', -2.0, unixepoch()),
('c239', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'elegance', 0.5, unixepoch()),
('c240', 'b6d2f8a0-1c3e-4b7f-8f0f-2e6c4a1d7f5b', 'customizability', 4.0, unixepoch()),

-- Ajiaco (785539f6-98be-4a22-8033-3f28d8396149)
('c241', '785539f6-98be-4a22-8033-3f28d8396149', 'crispiness', -4.5, unixepoch()),
('c242', '785539f6-98be-4a22-8033-3f28d8396149', 'richness', 2.0, unixepoch()),
('c243', '785539f6-98be-4a22-8033-3f28d8396149', 'flavor_complexity', 2.5, unixepoch()),
('c244', '785539f6-98be-4a22-8033-3f28d8396149', 'heartiness', 4.0, unixepoch()),
('c245', '785539f6-98be-4a22-8033-3f28d8396149', 'potato_prominence', 4.0, unixepoch()),
('c246', '785539f6-98be-4a22-8033-3f28d8396149', 'novelty', 3.5, unixepoch()),
('c247', '785539f6-98be-4a22-8033-3f28d8396149', 'elegance', 0.0, unixepoch()),
('c248', '785539f6-98be-4a22-8033-3f28d8396149', 'customizability', -1.0, unixepoch()),

-- Aligot (be4f8c34-64f7-47be-822c-2f00a22977b3)
('c249', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'crispiness', -5.0, unixepoch()),
('c250', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'richness', 5.0, unixepoch()),
('c251', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'flavor_complexity', 0.5, unixepoch()),
('c252', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'heartiness', 3.0, unixepoch()),
('c253', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'potato_prominence', 3.5, unixepoch()),
('c254', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'novelty', 3.0, unixepoch()),
('c255', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'elegance', 1.5, unixepoch()),
('c256', 'be4f8c34-64f7-47be-822c-2f00a22977b3', 'customizability', -2.5, unixepoch()),

-- Aloo gobi (436e323b-4898-4fd7-892c-9798d81f35ae)
('c257', '436e323b-4898-4fd7-892c-9798d81f35ae', 'crispiness', -1.5, unixepoch()),
('c258', '436e323b-4898-4fd7-892c-9798d81f35ae', 'richness', 0.0, unixepoch()),
('c259', '436e323b-4898-4fd7-892c-9798d81f35ae', 'flavor_complexity', 3.5, unixepoch()),
('c260', '436e323b-4898-4fd7-892c-9798d81f35ae', 'heartiness', 2.5, unixepoch()),
('c261', '436e323b-4898-4fd7-892c-9798d81f35ae', 'potato_prominence', 3.5, unixepoch()),
('c262', '436e323b-4898-4fd7-892c-9798d81f35ae', 'novelty', -0.5, unixepoch()),
('c263', '436e323b-4898-4fd7-892c-9798d81f35ae', 'elegance', -1.0, unixepoch()),
('c264', '436e323b-4898-4fd7-892c-9798d81f35ae', 'customizability', 0.0, unixepoch()),

-- Aloo gosht (9d6cfd5e-2d85-40b5-b746-de51e8fd04e1)
('c265', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'crispiness', -3.0, unixepoch()),
('c266', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'richness', 2.5, unixepoch()),
('c267', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'flavor_complexity', 3.0, unixepoch()),
('c268', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'heartiness', 4.5, unixepoch()),
('c269', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'potato_prominence', 2.5, unixepoch()),
('c270', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'novelty', 0.5, unixepoch()),
('c271', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'elegance', -1.0, unixepoch()),
('c272', '9d6cfd5e-2d85-40b5-b746-de51e8fd04e1', 'customizability', -0.5, unixepoch()),

-- Aloo pie (d7336300-3d6f-48bb-be6d-c68aa24d29f6)
('c273', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'crispiness', 2.0, unixepoch()),
('c274', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'richness', 1.5, unixepoch()),
('c275', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'flavor_complexity', 2.0, unixepoch()),
('c276', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'heartiness', 1.5, unixepoch()),
('c277', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'potato_prominence', 3.5, unixepoch()),
('c278', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'novelty', 3.0, unixepoch()),
('c279', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'elegance', -2.5, unixepoch()),
('c280', 'd7336300-3d6f-48bb-be6d-c68aa24d29f6', 'customizability', -1.0, unixepoch()),

-- Aloo posto (3f384d4d-bc42-4c46-a5b8-54b30477efee)
('c281', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'crispiness', -3.0, unixepoch()),
('c282', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'richness', 1.5, unixepoch()),
('c283', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'flavor_complexity', 2.5, unixepoch()),
('c284', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'heartiness', 1.5, unixepoch()),
('c285', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'potato_prominence', 4.5, unixepoch()),
('c286', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'novelty', 3.5, unixepoch()),
('c287', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'elegance', -0.5, unixepoch()),
('c288', '3f384d4d-bc42-4c46-a5b8-54b30477efee', 'customizability', -2.0, unixepoch()),

-- Älplermagronen (fd9ba604-89ec-42cb-8811-e78252f80690)
('c289', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'crispiness', -2.0, unixepoch()),
('c290', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'richness', 3.5, unixepoch()),
('c291', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'flavor_complexity', 1.0, unixepoch()),
('c292', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'heartiness', 4.0, unixepoch()),
('c293', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'potato_prominence', 2.0, unixepoch()),
('c294', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'novelty', 2.5, unixepoch()),
('c295', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'elegance', 0.0, unixepoch()),
('c296', 'fd9ba604-89ec-42cb-8811-e78252f80690', 'customizability', -1.0, unixepoch()),

-- Bangers and mash (8b53de88-0b2e-43b3-956c-78ec3f15c73c)
('c297', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'crispiness', -3.5, unixepoch()),
('c298', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'richness', 3.0, unixepoch()),
('c299', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'flavor_complexity', 1.5, unixepoch()),
('c300', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'heartiness', 4.5, unixepoch()),
('c301', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'potato_prominence', 3.0, unixepoch()),
('c302', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'novelty', -1.5, unixepoch()),
('c303', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'elegance', -2.0, unixepoch()),
('c304', '8b53de88-0b2e-43b3-956c-78ec3f15c73c', 'customizability', 0.5, unixepoch()),

-- Batatas a murro (989ff929-8368-4914-8645-e2007ca7106c)
('c305', '989ff929-8368-4914-8645-e2007ca7106c', 'crispiness', 1.5, unixepoch()),
('c306', '989ff929-8368-4914-8645-e2007ca7106c', 'richness', -2.5, unixepoch()),
('c307', '989ff929-8368-4914-8645-e2007ca7106c', 'flavor_complexity', 0.5, unixepoch()),
('c308', '989ff929-8368-4914-8645-e2007ca7106c', 'heartiness', 1.0, unixepoch()),
('c309', '989ff929-8368-4914-8645-e2007ca7106c', 'potato_prominence', 5.0, unixepoch()),
('c310', '989ff929-8368-4914-8645-e2007ca7106c', 'novelty', 2.5, unixepoch()),
('c311', '989ff929-8368-4914-8645-e2007ca7106c', 'elegance', 0.0, unixepoch()),
('c312', '989ff929-8368-4914-8645-e2007ca7106c', 'customizability', -2.0, unixepoch()),

-- Batata harra (4d88aa81-4a81-496e-b1d2-234a732098b9)
('c313', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'crispiness', 3.0, unixepoch()),
('c314', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'richness', 1.0, unixepoch()),
('c315', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'flavor_complexity', 3.0, unixepoch()),
('c316', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'heartiness', 1.0, unixepoch()),
('c317', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'potato_prominence', 4.5, unixepoch()),
('c318', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'novelty', 2.0, unixepoch()),
('c319', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'elegance', -1.0, unixepoch()),
('c320', '4d88aa81-4a81-496e-b1d2-234a732098b9', 'customizability', -1.0, unixepoch()),

-- Batata vada (0dd436f4-100e-4818-8744-e4e0ea31c4d8)
('c321', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'crispiness', 3.5, unixepoch()),
('c322', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'richness', 1.5, unixepoch()),
('c323', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'flavor_complexity', 2.0, unixepoch()),
('c324', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'heartiness', -1.0, unixepoch()),
('c325', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'potato_prominence', 4.0, unixepoch()),
('c326', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'novelty', 1.5, unixepoch()),
('c327', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'elegance', -2.5, unixepoch()),
('c328', '0dd436f4-100e-4818-8744-e4e0ea31c4d8', 'customizability', -1.5, unixepoch()),

-- Batates bechamel (327177e9-8641-40ef-89bd-1cbf1c2387d3)
('c329', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'crispiness', -2.0, unixepoch()),
('c330', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'richness', 3.5, unixepoch()),
('c331', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'flavor_complexity', 1.5, unixepoch()),
('c332', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'heartiness', 4.0, unixepoch()),
('c333', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'potato_prominence', 3.5, unixepoch()),
('c334', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'novelty', 2.5, unixepoch()),
('c335', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'elegance', 0.0, unixepoch()),
('c336', '327177e9-8641-40ef-89bd-1cbf1c2387d3', 'customizability', -1.0, unixepoch()),

-- Bauernfrühstück (ae5c5502-480d-4aeb-8b7e-73380f10bd1f)
('c337', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'crispiness', 2.5, unixepoch()),
('c338', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'richness', 2.5, unixepoch()),
('c339', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'flavor_complexity', 1.0, unixepoch()),
('c340', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'heartiness', 3.5, unixepoch()),
('c341', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'potato_prominence', 3.0, unixepoch()),
('c342', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'novelty', 2.0, unixepoch()),
('c343', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'elegance', -2.5, unixepoch()),
('c344', 'ae5c5502-480d-4aeb-8b7e-73380f10bd1f', 'customizability', 1.0, unixepoch()),

-- Bombay potatoes (6d06d0e8-6907-4311-931b-13af3a7b81c7)
('c345', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'crispiness', 1.5, unixepoch()),
('c346', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'richness', 0.5, unixepoch()),
('c347', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'flavor_complexity', 3.0, unixepoch()),
('c348', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'heartiness', 1.0, unixepoch()),
('c349', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'potato_prominence', 4.5, unixepoch()),
('c350', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'novelty', -0.5, unixepoch()),
('c351', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'elegance', -1.5, unixepoch()),
('c352', '6d06d0e8-6907-4311-931b-13af3a7b81c7', 'customizability', 0.5, unixepoch()),

-- Boulangère potatoes (3a9926a1-69b6-475f-83dc-99817faa9ad2)
('c353', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'crispiness', -0.5, unixepoch()),
('c354', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'richness', 1.5, unixepoch()),
('c355', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'flavor_complexity', 1.0, unixepoch()),
('c356', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'heartiness', 2.5, unixepoch()),
('c357', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'potato_prominence', 4.5, unixepoch()),
('c358', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'novelty', 1.5, unixepoch()),
('c359', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'elegance', 1.5, unixepoch()),
('c360', '3a9926a1-69b6-475f-83dc-99817faa9ad2', 'customizability', -2.0, unixepoch()),

-- Bonda (a475c9b3-1419-42d9-82be-237d58a79a8d)
('c361', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'crispiness', 3.0, unixepoch()),
('c362', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'richness', 1.5, unixepoch()),
('c363', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'flavor_complexity', 2.5, unixepoch()),
('c364', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'heartiness', -1.0, unixepoch()),
('c365', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'potato_prominence', 3.5, unixepoch()),
('c366', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'novelty', 2.5, unixepoch()),
('c367', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'elegance', -2.5, unixepoch()),
('c368', 'a475c9b3-1419-42d9-82be-237d58a79a8d', 'customizability', -1.5, unixepoch()),

-- Bubble and squeak (0358bec7-de8b-4fc4-a222-294b01fa90f7)
('c369', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'crispiness', 3.0, unixepoch()),
('c370', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'richness', 1.5, unixepoch()),
('c371', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'flavor_complexity', -0.5, unixepoch()),
('c372', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'heartiness', 2.0, unixepoch()),
('c373', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'potato_prominence', 3.5, unixepoch()),
('c374', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'novelty', -0.5, unixepoch()),
('c375', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'elegance', -3.0, unixepoch()),
('c376', '0358bec7-de8b-4fc4-a222-294b01fa90f7', 'customizability', 2.0, unixepoch()),

-- Cacasse à cul nu (40c52835-9537-453f-8093-71a324979dfe)
('c377', '40c52835-9537-453f-8093-71a324979dfe', 'crispiness', -2.5, unixepoch()),
('c378', '40c52835-9537-453f-8093-71a324979dfe', 'richness', 2.0, unixepoch()),
('c379', '40c52835-9537-453f-8093-71a324979dfe', 'flavor_complexity', 1.0, unixepoch()),
('c380', '40c52835-9537-453f-8093-71a324979dfe', 'heartiness', 4.0, unixepoch()),
('c381', '40c52835-9537-453f-8093-71a324979dfe', 'potato_prominence', 4.5, unixepoch()),
('c382', '40c52835-9537-453f-8093-71a324979dfe', 'novelty', 4.5, unixepoch()),
('c383', '40c52835-9537-453f-8093-71a324979dfe', 'elegance', -3.0, unixepoch()),
('c384', '40c52835-9537-453f-8093-71a324979dfe', 'customizability', -1.0, unixepoch()),

-- Canarian wrinkly potatoes (b3515faf-60f3-4c74-8f26-aeb9933a08dd)
('c385', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'crispiness', 1.0, unixepoch()),
('c386', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'richness', -1.5, unixepoch()),
('c387', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'flavor_complexity', 1.5, unixepoch()),
('c388', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'heartiness', 1.0, unixepoch()),
('c389', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'potato_prominence', 5.0, unixepoch()),
('c390', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'novelty', 1.5, unixepoch()),
('c391', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'elegance', -0.5, unixepoch()),
('c392', 'b3515faf-60f3-4c74-8f26-aeb9933a08dd', 'customizability', -2.5, unixepoch()),

-- Carne asada fries (9f2bd161-4945-434b-ac8e-afb036295973)
('c393', '9f2bd161-4945-434b-ac8e-afb036295973', 'crispiness', 3.5, unixepoch()),
('c394', '9f2bd161-4945-434b-ac8e-afb036295973', 'richness', 3.0, unixepoch()),
('c395', '9f2bd161-4945-434b-ac8e-afb036295973', 'flavor_complexity', 2.0, unixepoch()),
('c396', '9f2bd161-4945-434b-ac8e-afb036295973', 'heartiness', 3.5, unixepoch()),
('c397', '9f2bd161-4945-434b-ac8e-afb036295973', 'potato_prominence', 2.5, unixepoch()),
('c398', '9f2bd161-4945-434b-ac8e-afb036295973', 'novelty', -1.0, unixepoch()),
('c399', '9f2bd161-4945-434b-ac8e-afb036295973', 'elegance', -4.0, unixepoch()),
('c400', '9f2bd161-4945-434b-ac8e-afb036295973', 'customizability', 2.0, unixepoch()),

-- Cepelinai (c8488053-7889-4d0b-aa4d-13ee5c7743d2)
('c401', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'crispiness', -2.5, unixepoch()),
('c402', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'richness', 3.0, unixepoch()),
('c403', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'flavor_complexity', 1.0, unixepoch()),
('c404', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'heartiness', 4.5, unixepoch()),
('c405', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'potato_prominence', 4.5, unixepoch()),
('c406', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'novelty', 4.0, unixepoch()),
('c407', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'elegance', -0.5, unixepoch()),
('c408', 'c8488053-7889-4d0b-aa4d-13ee5c7743d2', 'customizability', -2.5, unixepoch()),

-- Chapalele (7d0db129-ad99-4d33-8b21-de28c116b181)
('c409', '7d0db129-ad99-4d33-8b21-de28c116b181', 'crispiness', -2.0, unixepoch()),
('c410', '7d0db129-ad99-4d33-8b21-de28c116b181', 'richness', 1.0, unixepoch()),
('c411', '7d0db129-ad99-4d33-8b21-de28c116b181', 'flavor_complexity', -1.0, unixepoch()),
('c412', '7d0db129-ad99-4d33-8b21-de28c116b181', 'heartiness', 2.0, unixepoch()),
('c413', '7d0db129-ad99-4d33-8b21-de28c116b181', 'potato_prominence', 4.5, unixepoch()),
('c414', '7d0db129-ad99-4d33-8b21-de28c116b181', 'novelty', 4.5, unixepoch()),
('c415', '7d0db129-ad99-4d33-8b21-de28c116b181', 'elegance', -2.0, unixepoch()),
('c416', '7d0db129-ad99-4d33-8b21-de28c116b181', 'customizability', -2.5, unixepoch()),

-- Cheese fries (3b25a411-326c-4a1d-bec4-d24232179a48)
('c417', '3b25a411-326c-4a1d-bec4-d24232179a48', 'crispiness', 3.5, unixepoch()),
('c418', '3b25a411-326c-4a1d-bec4-d24232179a48', 'richness', 3.0, unixepoch()),
('c419', '3b25a411-326c-4a1d-bec4-d24232179a48', 'flavor_complexity', -0.5, unixepoch()),
('c420', '3b25a411-326c-4a1d-bec4-d24232179a48', 'heartiness', 1.5, unixepoch()),
('c421', '3b25a411-326c-4a1d-bec4-d24232179a48', 'potato_prominence', 3.5, unixepoch()),
('c422', '3b25a411-326c-4a1d-bec4-d24232179a48', 'novelty', -3.5, unixepoch()),
('c423', '3b25a411-326c-4a1d-bec4-d24232179a48', 'elegance', -4.5, unixepoch()),
('c424', '3b25a411-326c-4a1d-bec4-d24232179a48', 'customizability', 1.5, unixepoch()),

-- Chips and dip (6a861229-6712-4b8a-a154-8144a8bca88c)
('c425', '6a861229-6712-4b8a-a154-8144a8bca88c', 'crispiness', 5.0, unixepoch()),
('c426', '6a861229-6712-4b8a-a154-8144a8bca88c', 'richness', 1.5, unixepoch()),
('c427', '6a861229-6712-4b8a-a154-8144a8bca88c', 'flavor_complexity', 1.0, unixepoch()),
('c428', '6a861229-6712-4b8a-a154-8144a8bca88c', 'heartiness', -3.5, unixepoch()),
('c429', '6a861229-6712-4b8a-a154-8144a8bca88c', 'potato_prominence', 3.0, unixepoch()),
('c430', '6a861229-6712-4b8a-a154-8144a8bca88c', 'novelty', -4.0, unixepoch()),
('c431', '6a861229-6712-4b8a-a154-8144a8bca88c', 'elegance', -4.0, unixepoch()),
('c432', '6a861229-6712-4b8a-a154-8144a8bca88c', 'customizability', 3.5, unixepoch()),

-- Chocolate-covered potato chips (c868b277-1c62-4b89-8343-90e35e2da9d4)
('c433', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'crispiness', 4.0, unixepoch()),
('c434', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'richness', 2.5, unixepoch()),
('c435', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'flavor_complexity', 1.5, unixepoch()),
('c436', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'heartiness', -4.5, unixepoch()),
('c437', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'potato_prominence', 2.0, unixepoch()),
('c438', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'novelty', 2.0, unixepoch()),
('c439', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'elegance', -1.0, unixepoch()),
('c440', 'c868b277-1c62-4b89-8343-90e35e2da9d4', 'customizability', -2.5, unixepoch()),

-- Chorrillana (ee91cd60-3c05-43c1-9fa9-7a725f68b35a)
('c441', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'crispiness', 3.5, unixepoch()),
('c442', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'richness', 3.5, unixepoch()),
('c443', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'flavor_complexity', 2.0, unixepoch()),
('c444', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'heartiness', 5.0, unixepoch()),
('c445', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'potato_prominence', 2.5, unixepoch()),
('c446', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'novelty', 2.0, unixepoch()),
('c447', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'elegance', -4.0, unixepoch()),
('c448', 'ee91cd60-3c05-43c1-9fa9-7a725f68b35a', 'customizability', -0.5, unixepoch()),

-- Clapshot (8edd9660-f8ba-4fd2-bcda-5b516ce592fc)
('c449', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'crispiness', -4.0, unixepoch()),
('c450', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'richness', 1.5, unixepoch()),
('c451', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'flavor_complexity', 0.5, unixepoch()),
('c452', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'heartiness', 2.0, unixepoch()),
('c453', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'potato_prominence', 4.0, unixepoch()),
('c454', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'novelty', 1.5, unixepoch()),
('c455', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'elegance', -1.5, unixepoch()),
('c456', '8edd9660-f8ba-4fd2-bcda-5b516ce592fc', 'customizability', -1.0, unixepoch()),

-- Coddle (275d7111-b716-4c3c-9318-1eacdd9b726d)
('c457', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'crispiness', -4.0, unixepoch()),
('c458', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'richness', 2.5, unixepoch()),
('c459', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'flavor_complexity', 0.5, unixepoch()),
('c460', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'heartiness', 4.0, unixepoch()),
('c461', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'potato_prominence', 2.5, unixepoch()),
('c462', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'novelty', 2.0, unixepoch()),
('c463', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'elegance', -2.5, unixepoch()),
('c464', '275d7111-b716-4c3c-9318-1eacdd9b726d', 'customizability', -1.0, unixepoch()),

-- Cottage pie (822148f1-54d4-41f3-9407-8d1d37d6bc0f)
('c465', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'crispiness', -1.5, unixepoch()),
('c466', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'richness', 3.0, unixepoch()),
('c467', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'flavor_complexity', 1.5, unixepoch()),
('c468', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'heartiness', 5.0, unixepoch()),
('c469', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'potato_prominence', 2.5, unixepoch()),
('c470', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'novelty', -2.0, unixepoch()),
('c471', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'elegance', -0.5, unixepoch()),
('c472', '822148f1-54d4-41f3-9407-8d1d37d6bc0f', 'customizability', 0.5, unixepoch()),

-- Crisp sandwich (60883922-05ae-466e-bdb9-91006244105c)
('c473', '60883922-05ae-466e-bdb9-91006244105c', 'crispiness', 4.5, unixepoch()),
('c474', '60883922-05ae-466e-bdb9-91006244105c', 'richness', 0.5, unixepoch()),
('c475', '60883922-05ae-466e-bdb9-91006244105c', 'flavor_complexity', -1.5, unixepoch()),
('c476', '60883922-05ae-466e-bdb9-91006244105c', 'heartiness', -2.5, unixepoch()),
('c477', '60883922-05ae-466e-bdb9-91006244105c', 'potato_prominence', 2.0, unixepoch()),
('c478', '60883922-05ae-466e-bdb9-91006244105c', 'novelty', 1.0, unixepoch()),
('c479', '60883922-05ae-466e-bdb9-91006244105c', 'elegance', -5.0, unixepoch()),
('c480', '60883922-05ae-466e-bdb9-91006244105c', 'customizability', 1.5, unixepoch()),

-- Crocchè (70e6a1ef-e59f-470b-9a8b-8f825b608b19)
('c481', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'crispiness', 3.5, unixepoch()),
('c482', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'richness', 2.0, unixepoch()),
('c483', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'flavor_complexity', 0.0, unixepoch()),
('c484', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'heartiness', -0.5, unixepoch()),
('c485', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'potato_prominence', 4.0, unixepoch()),
('c486', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'novelty', 2.0, unixepoch()),
('c487', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'elegance', -2.0, unixepoch()),
('c488', '70e6a1ef-e59f-470b-9a8b-8f825b608b19', 'customizability', -0.5, unixepoch()),

-- Dabeli (8b584a3e-37ca-4f3d-af8f-89014a53c581)
('c489', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'crispiness', 1.5, unixepoch()),
('c490', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'richness', 1.0, unixepoch()),
('c491', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'flavor_complexity', 3.0, unixepoch()),
('c492', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'heartiness', 0.5, unixepoch()),
('c493', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'potato_prominence', 3.5, unixepoch()),
('c494', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'novelty', 2.5, unixepoch()),
('c495', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'elegance', -3.0, unixepoch()),
('c496', '8b584a3e-37ca-4f3d-af8f-89014a53c581', 'customizability', -1.0, unixepoch()),

-- Disco fries (cf2fc462-5619-43c0-9916-fa3cafb216f3)
('c497', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'crispiness', 2.5, unixepoch()),
('c498', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'richness', 3.5, unixepoch()),
('c499', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'flavor_complexity', 0.0, unixepoch()),
('c500', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'heartiness', 2.5, unixepoch()),
('c501', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'potato_prominence', 2.5, unixepoch()),
('c502', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'novelty', 0.5, unixepoch()),
('c503', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'elegance', -4.0, unixepoch()),
('c504', 'cf2fc462-5619-43c0-9916-fa3cafb216f3', 'customizability', 0.5, unixepoch()),

-- Duchess potatoes (8dd02f58-92de-48de-b5ff-a513e1126fc5)
('c505', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'crispiness', 2.0, unixepoch()),
('c506', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'richness', 3.5, unixepoch()),
('c507', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'flavor_complexity', 0.0, unixepoch()),
('c508', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'heartiness', 1.5, unixepoch()),
('c509', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'potato_prominence', 5.0, unixepoch()),
('c510', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'novelty', 0.5, unixepoch()),
('c511', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'elegance', 4.0, unixepoch()),
('c512', '8dd02f58-92de-48de-b5ff-a513e1126fc5', 'customizability', -2.5, unixepoch()),

-- Dum aloo (8171ea87-7217-4d34-b9ce-338de7e25db4)
('c513', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'crispiness', 1.5, unixepoch()),
('c514', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'richness', 2.0, unixepoch()),
('c515', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'flavor_complexity', 4.0, unixepoch()),
('c516', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'heartiness', 2.5, unixepoch()),
('c517', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'potato_prominence', 5.0, unixepoch()),
('c518', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'novelty', 0.5, unixepoch()),
('c519', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'elegance', 0.5, unixepoch()),
('c520', '8171ea87-7217-4d34-b9ce-338de7e25db4', 'customizability', -1.0, unixepoch()),

-- Far far (848a2f87-41f6-46b1-9268-71cff8f31212)
('c521', '848a2f87-41f6-46b1-9268-71cff8f31212', 'crispiness', 5.0, unixepoch()),
('c522', '848a2f87-41f6-46b1-9268-71cff8f31212', 'richness', 0.5, unixepoch()),
('c523', '848a2f87-41f6-46b1-9268-71cff8f31212', 'flavor_complexity', 0.5, unixepoch()),
('c524', '848a2f87-41f6-46b1-9268-71cff8f31212', 'heartiness', -4.5, unixepoch()),
('c525', '848a2f87-41f6-46b1-9268-71cff8f31212', 'potato_prominence', 1.5, unixepoch()),
('c526', '848a2f87-41f6-46b1-9268-71cff8f31212', 'novelty', 3.5, unixepoch()),
('c527', '848a2f87-41f6-46b1-9268-71cff8f31212', 'elegance', -2.5, unixepoch()),
('c528', '848a2f87-41f6-46b1-9268-71cff8f31212', 'customizability', -2.5, unixepoch()),

-- Fondant potatoes (9b31b3c9-9237-472c-998a-b4e4c00e71be)
('c529', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'crispiness', 1.0, unixepoch()),
('c530', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'richness', 3.5, unixepoch()),
('c531', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'flavor_complexity', 1.0, unixepoch()),
('c532', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'heartiness', 2.0, unixepoch()),
('c533', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'potato_prominence', 5.0, unixepoch()),
('c534', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'novelty', 1.0, unixepoch()),
('c535', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'elegance', 4.5, unixepoch()),
('c536', '9b31b3c9-9237-472c-998a-b4e4c00e71be', 'customizability', -3.0, unixepoch()),

-- Gamja ongsimi (8db5f070-0889-4a13-95ff-a72938efcae9)
('c537', '8db5f070-0889-4a13-95ff-a72938efcae9', 'crispiness', -4.0, unixepoch()),
('c538', '8db5f070-0889-4a13-95ff-a72938efcae9', 'richness', 1.0, unixepoch()),
('c539', '8db5f070-0889-4a13-95ff-a72938efcae9', 'flavor_complexity', 1.5, unixepoch()),
('c540', '8db5f070-0889-4a13-95ff-a72938efcae9', 'heartiness', 3.5, unixepoch()),
('c541', '8db5f070-0889-4a13-95ff-a72938efcae9', 'potato_prominence', 4.0, unixepoch()),
('c542', '8db5f070-0889-4a13-95ff-a72938efcae9', 'novelty', 4.5, unixepoch()),
('c543', '8db5f070-0889-4a13-95ff-a72938efcae9', 'elegance', 0.0, unixepoch()),
('c544', '8db5f070-0889-4a13-95ff-a72938efcae9', 'customizability', -2.0, unixepoch()),

-- Halal snack pack (5a83e62d-0795-4944-9fa4-35996d36bdeb)
('c545', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'crispiness', 3.5, unixepoch()),
('c546', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'richness', 3.5, unixepoch()),
('c547', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'flavor_complexity', 2.0, unixepoch()),
('c548', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'heartiness', 4.5, unixepoch()),
('c549', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'potato_prominence', 2.0, unixepoch()),
('c550', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'novelty', 0.5, unixepoch()),
('c551', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'elegance', -4.5, unixepoch()),
('c552', '5a83e62d-0795-4944-9fa4-35996d36bdeb', 'customizability', 1.0, unixepoch()),

-- Hasselback Potatoes (a7450913-aba9-422c-84fa-64bc1f3a24b0)
('c553', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'crispiness', 3.0, unixepoch()),
('c554', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'richness', 2.0, unixepoch()),
('c555', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'flavor_complexity', 0.5, unixepoch()),
('c556', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'heartiness', 2.0, unixepoch()),
('c557', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'potato_prominence', 5.0, unixepoch()),
('c558', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'novelty', -0.5, unixepoch()),
('c559', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'elegance', 2.5, unixepoch()),
('c560', 'a7450913-aba9-422c-84fa-64bc1f3a24b0', 'customizability', 2.0, unixepoch()),

-- Home fries (15732175-feb8-4a06-afbe-62dc3c82185e)
('c561', '15732175-feb8-4a06-afbe-62dc3c82185e', 'crispiness', 2.5, unixepoch()),
('c562', '15732175-feb8-4a06-afbe-62dc3c82185e', 'richness', 1.5, unixepoch()),
('c563', '15732175-feb8-4a06-afbe-62dc3c82185e', 'flavor_complexity', -1.0, unixepoch()),
('c564', '15732175-feb8-4a06-afbe-62dc3c82185e', 'heartiness', 1.0, unixepoch()),
('c565', '15732175-feb8-4a06-afbe-62dc3c82185e', 'potato_prominence', 4.5, unixepoch()),
('c566', '15732175-feb8-4a06-afbe-62dc3c82185e', 'novelty', -3.5, unixepoch()),
('c567', '15732175-feb8-4a06-afbe-62dc3c82185e', 'elegance', -3.5, unixepoch()),
('c568', '15732175-feb8-4a06-afbe-62dc3c82185e', 'customizability', 1.0, unixepoch()),

-- Knödel (864d1450-4f9a-4155-9c91-95d43f70b313)
('c569', '864d1450-4f9a-4155-9c91-95d43f70b313', 'crispiness', -4.0, unixepoch()),
('c570', '864d1450-4f9a-4155-9c91-95d43f70b313', 'richness', 2.0, unixepoch()),
('c571', '864d1450-4f9a-4155-9c91-95d43f70b313', 'flavor_complexity', -0.5, unixepoch()),
('c572', '864d1450-4f9a-4155-9c91-95d43f70b313', 'heartiness', 2.5, unixepoch()),
('c573', '864d1450-4f9a-4155-9c91-95d43f70b313', 'potato_prominence', 3.5, unixepoch()),
('c574', '864d1450-4f9a-4155-9c91-95d43f70b313', 'novelty', 1.0, unixepoch()),
('c575', '864d1450-4f9a-4155-9c91-95d43f70b313', 'elegance', 0.0, unixepoch()),
('c576', '864d1450-4f9a-4155-9c91-95d43f70b313', 'customizability', -1.5, unixepoch()),

-- Kopytka (96545002-0d3c-4739-9074-a5d630bf9e6a)
('c577', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'crispiness', -3.0, unixepoch()),
('c578', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'richness', 1.5, unixepoch()),
('c579', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'flavor_complexity', -1.5, unixepoch()),
('c580', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'heartiness', 2.5, unixepoch()),
('c581', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'potato_prominence', 4.5, unixepoch()),
('c582', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'novelty', 2.0, unixepoch()),
('c583', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'elegance', -0.5, unixepoch()),
('c584', '96545002-0d3c-4739-9074-a5d630bf9e6a', 'customizability', 0.5, unixepoch()),

-- Korokke (fe63cd3e-2051-4881-9a4b-81eb0546800c)
('c585', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'crispiness', 3.5, unixepoch()),
('c586', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'richness', 2.0, unixepoch()),
('c587', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'flavor_complexity', 1.0, unixepoch()),
('c588', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'heartiness', 0.5, unixepoch()),
('c589', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'potato_prominence', 3.5, unixepoch()),
('c590', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'novelty', 0.0, unixepoch()),
('c591', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'elegance', -1.0, unixepoch()),
('c592', 'fe63cd3e-2051-4881-9a4b-81eb0546800c', 'customizability', -1.0, unixepoch()),

-- Kroppkaka (ab08c0b6-083c-4653-a6d1-7b7debc48256)
('c593', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'crispiness', -3.5, unixepoch()),
('c594', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'richness', 2.5, unixepoch()),
('c595', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'flavor_complexity', 0.0, unixepoch()),
('c596', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'heartiness', 4.0, unixepoch()),
('c597', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'potato_prominence', 4.5, unixepoch()),
('c598', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'novelty', 4.0, unixepoch()),
('c599', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'elegance', -0.5, unixepoch()),
('c600', 'ab08c0b6-083c-4653-a6d1-7b7debc48256', 'customizability', -3.0, unixepoch()),

-- Kugel (8756548c-c91e-4548-89de-33842719228f)
('c601', '8756548c-c91e-4548-89de-33842719228f', 'crispiness', -2.0, unixepoch()),
('c602', '8756548c-c91e-4548-89de-33842719228f', 'richness', 3.0, unixepoch()),
('c603', '8756548c-c91e-4548-89de-33842719228f', 'flavor_complexity', -1.0, unixepoch()),
('c604', '8756548c-c91e-4548-89de-33842719228f', 'heartiness', 3.0, unixepoch()),
('c605', '8756548c-c91e-4548-89de-33842719228f', 'potato_prominence', 3.5, unixepoch()),
('c606', '8756548c-c91e-4548-89de-33842719228f', 'novelty', 0.5, unixepoch()),
('c607', '8756548c-c91e-4548-89de-33842719228f', 'elegance', -0.5, unixepoch()),
('c608', '8756548c-c91e-4548-89de-33842719228f', 'customizability', -1.0, unixepoch()),

-- Meat and potato pie (98f0a34c-ea71-4a65-b35e-67b3768e8c7e)
('c609', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'crispiness', 1.0, unixepoch()),
('c610', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'richness', 2.5, unixepoch()),
('c611', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'flavor_complexity', 1.0, unixepoch()),
('c612', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'heartiness', 4.5, unixepoch()),
('c613', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'potato_prominence', 2.5, unixepoch()),
('c614', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'novelty', -1.0, unixepoch()),
('c615', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'elegance', -2.0, unixepoch()),
('c616', '98f0a34c-ea71-4a65-b35e-67b3768e8c7e', 'customizability', -0.5, unixepoch()),

-- Nikujaga (b7894ef6-354b-4a37-a73a-a9a14c0efb50)
('c617', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'crispiness', -4.0, unixepoch()),
('c618', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'richness', 1.5, unixepoch()),
('c619', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'flavor_complexity', 2.5, unixepoch()),
('c620', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'heartiness', 4.0, unixepoch()),
('c621', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'potato_prominence', 3.5, unixepoch()),
('c622', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'novelty', 2.0, unixepoch()),
('c623', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'elegance', -0.5, unixepoch()),
('c624', 'b7894ef6-354b-4a37-a73a-a9a14c0efb50', 'customizability', -1.0, unixepoch()),

-- Nilaga (78063773-32b5-4ed9-9273-bedec6114f6b)
('c625', '78063773-32b5-4ed9-9273-bedec6114f6b', 'crispiness', -4.5, unixepoch()),
('c626', '78063773-32b5-4ed9-9273-bedec6114f6b', 'richness', 1.5, unixepoch()),
('c627', '78063773-32b5-4ed9-9273-bedec6114f6b', 'flavor_complexity', 1.0, unixepoch()),
('c628', '78063773-32b5-4ed9-9273-bedec6114f6b', 'heartiness', 4.5, unixepoch()),
('c629', '78063773-32b5-4ed9-9273-bedec6114f6b', 'potato_prominence', 3.0, unixepoch()),
('c630', '78063773-32b5-4ed9-9273-bedec6114f6b', 'novelty', 2.5, unixepoch()),
('c631', '78063773-32b5-4ed9-9273-bedec6114f6b', 'elegance', -1.0, unixepoch()),
('c632', '78063773-32b5-4ed9-9273-bedec6114f6b', 'customizability', -0.5, unixepoch()),

-- Okroshka (64700da3-9866-44da-8f95-738f5a8afb1d)
('c633', '64700da3-9866-44da-8f95-738f5a8afb1d', 'crispiness', -4.5, unixepoch()),
('c634', '64700da3-9866-44da-8f95-738f5a8afb1d', 'richness', 1.0, unixepoch()),
('c635', '64700da3-9866-44da-8f95-738f5a8afb1d', 'flavor_complexity', 2.0, unixepoch()),
('c636', '64700da3-9866-44da-8f95-738f5a8afb1d', 'heartiness', 2.0, unixepoch()),
('c637', '64700da3-9866-44da-8f95-738f5a8afb1d', 'potato_prominence', 2.5, unixepoch()),
('c638', '64700da3-9866-44da-8f95-738f5a8afb1d', 'novelty', 3.0, unixepoch()),
('c639', '64700da3-9866-44da-8f95-738f5a8afb1d', 'elegance', -1.5, unixepoch()),
('c640', '64700da3-9866-44da-8f95-738f5a8afb1d', 'customizability', -0.5, unixepoch()),

-- Olivier salad (06a7831b-bce7-40f0-921c-14774c00dbfb)
('c641', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'crispiness', -3.5, unixepoch()),
('c642', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'richness', 2.0, unixepoch()),
('c643', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'flavor_complexity', 1.5, unixepoch()),
('c644', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'heartiness', 2.0, unixepoch()),
('c645', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'potato_prominence', 2.5, unixepoch()),
('c646', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'novelty', -1.0, unixepoch()),
('c647', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'elegance', -1.5, unixepoch()),
('c648', '06a7831b-bce7-40f0-921c-14774c00dbfb', 'customizability', -1.0, unixepoch()),

-- Papa rellena (ee44f68c-0446-45fa-9471-9e6041646e86)
('c649', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'crispiness', 3.5, unixepoch()),
('c650', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'richness', 2.5, unixepoch()),
('c651', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'flavor_complexity', 2.0, unixepoch()),
('c652', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'heartiness', 2.5, unixepoch()),
('c653', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'potato_prominence', 4.0, unixepoch()),
('c654', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'novelty', 2.0, unixepoch()),
('c655', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'elegance', -2.0, unixepoch()),
('c656', 'ee44f68c-0446-45fa-9471-9e6041646e86', 'customizability', -1.5, unixepoch()),

-- Pickert (bd3f208c-0432-4124-96b5-0c303e50009b)
('c657', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'crispiness', 2.0, unixepoch()),
('c658', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'richness', 1.5, unixepoch()),
('c659', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'flavor_complexity', -0.5, unixepoch()),
('c660', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'heartiness', 1.5, unixepoch()),
('c661', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'potato_prominence', 4.0, unixepoch()),
('c662', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'novelty', 3.5, unixepoch()),
('c663', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'elegance', -2.5, unixepoch()),
('c664', 'bd3f208c-0432-4124-96b5-0c303e50009b', 'customizability', 0.0, unixepoch()),

-- Pommes dauphine (730fa480-f456-46d7-9203-4dc5a913dce2)
('c665', '730fa480-f456-46d7-9203-4dc5a913dce2', 'crispiness', 4.0, unixepoch()),
('c666', '730fa480-f456-46d7-9203-4dc5a913dce2', 'richness', 3.0, unixepoch()),
('c667', '730fa480-f456-46d7-9203-4dc5a913dce2', 'flavor_complexity', -0.5, unixepoch()),
('c668', '730fa480-f456-46d7-9203-4dc5a913dce2', 'heartiness', -0.5, unixepoch()),
('c669', '730fa480-f456-46d7-9203-4dc5a913dce2', 'potato_prominence', 3.5, unixepoch()),
('c670', '730fa480-f456-46d7-9203-4dc5a913dce2', 'novelty', 1.0, unixepoch()),
('c671', '730fa480-f456-46d7-9203-4dc5a913dce2', 'elegance', 2.5, unixepoch()),
('c672', '730fa480-f456-46d7-9203-4dc5a913dce2', 'customizability', -2.0, unixepoch()),

-- Pommes soufflées (db9533ba-36e5-4894-8c97-f91ac02a87c7)
('c673', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'crispiness', 5.0, unixepoch()),
('c674', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'richness', 1.5, unixepoch()),
('c675', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'flavor_complexity', -2.0, unixepoch()),
('c676', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'heartiness', -2.5, unixepoch()),
('c677', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'potato_prominence', 5.0, unixepoch()),
('c678', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'novelty', 2.0, unixepoch()),
('c679', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'elegance', 4.0, unixepoch()),
('c680', 'db9533ba-36e5-4894-8c97-f91ac02a87c7', 'customizability', -4.0, unixepoch()),

-- Potato bread (807433ce-98aa-416c-a6d0-a130caa1c0fd)
('c681', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'crispiness', 0.5, unixepoch()),
('c682', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'richness', 0.5, unixepoch()),
('c683', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'flavor_complexity', -2.0, unixepoch()),
('c684', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'heartiness', -0.5, unixepoch()),
('c685', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'potato_prominence', 2.5, unixepoch()),
('c686', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'novelty', -1.5, unixepoch()),
('c687', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'elegance', -1.5, unixepoch()),
('c688', '807433ce-98aa-416c-a6d0-a130caa1c0fd', 'customizability', 1.0, unixepoch()),

-- Potato candy (07e057e6-7d58-4010-bc4a-1a6150a93012)
('c689', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'crispiness', -2.0, unixepoch()),
('c690', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'richness', 3.5, unixepoch()),
('c691', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'flavor_complexity', -0.5, unixepoch()),
('c692', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'heartiness', -4.5, unixepoch()),
('c693', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'potato_prominence', 1.5, unixepoch()),
('c694', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'novelty', 4.0, unixepoch()),
('c695', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'elegance', -2.0, unixepoch()),
('c696', '07e057e6-7d58-4010-bc4a-1a6150a93012', 'customizability', -2.5, unixepoch()),

-- Potato doughnut (b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b)
('c697', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'crispiness', 1.0, unixepoch()),
('c698', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'richness', 3.0, unixepoch()),
('c699', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'flavor_complexity', -1.5, unixepoch()),
('c700', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'heartiness', -3.0, unixepoch()),
('c701', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'potato_prominence', 2.0, unixepoch()),
('c702', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'novelty', 2.5, unixepoch()),
('c703', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'elegance', -2.0, unixepoch()),
('c704', 'b2b4e72f-7060-4d2e-82bf-f9e4a5c2e46b', 'customizability', -1.0, unixepoch()),

-- Potato filling (d5ede357-0627-464a-8ccc-158aed7a23d3)
('c705', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'crispiness', -3.0, unixepoch()),
('c706', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'richness', 1.5, unixepoch()),
('c707', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'flavor_complexity', -0.5, unixepoch()),
('c708', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'heartiness', 1.5, unixepoch()),
('c709', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'potato_prominence', 4.0, unixepoch()),
('c710', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'novelty', 2.0, unixepoch()),
('c711', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'elegance', -2.0, unixepoch()),
('c712', 'd5ede357-0627-464a-8ccc-158aed7a23d3', 'customizability', -0.5, unixepoch()),

-- Potato scone (e660f55e-1f42-4692-ae3b-7017622fa40f)
('c713', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'crispiness', 1.0, unixepoch()),
('c714', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'richness', 0.5, unixepoch()),
('c715', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'flavor_complexity', -2.5, unixepoch()),
('c716', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'heartiness', 0.0, unixepoch()),
('c717', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'potato_prominence', 4.0, unixepoch()),
('c718', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'novelty', 1.0, unixepoch()),
('c719', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'elegance', -2.5, unixepoch()),
('c720', 'e660f55e-1f42-4692-ae3b-7017622fa40f', 'customizability', 0.5, unixepoch()),

-- Potato waffle (d8abbffc-393e-4c06-b257-32ddccc7edee)
('c721', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'crispiness', 3.5, unixepoch()),
('c722', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'richness', 1.5, unixepoch()),
('c723', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'flavor_complexity', -1.5, unixepoch()),
('c724', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'heartiness', -1.0, unixepoch()),
('c725', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'potato_prominence', 4.0, unixepoch()),
('c726', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'novelty', 0.5, unixepoch()),
('c727', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'elegance', -2.5, unixepoch()),
('c728', 'd8abbffc-393e-4c06-b257-32ddccc7edee', 'customizability', -1.0, unixepoch()),

-- Poutine (8fcb5b3a-0ae0-438b-85e6-2ceec36b070f)
('c729', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'crispiness', 3.0, unixepoch()),
('c730', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'richness', 4.0, unixepoch()),
('c731', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'flavor_complexity', 1.0, unixepoch()),
('c732', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'heartiness', 3.5, unixepoch()),
('c733', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'potato_prominence', 3.0, unixepoch()),
('c734', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'novelty', -1.5, unixepoch()),
('c735', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'elegance', -3.5, unixepoch()),
('c736', '8fcb5b3a-0ae0-438b-85e6-2ceec36b070f', 'customizability', 1.0, unixepoch()),

-- Rumbledethumps (2e6b4457-6c93-4323-a91a-ff8266b30b69)
('c737', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'crispiness', -1.0, unixepoch()),
('c738', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'richness', 2.0, unixepoch()),
('c739', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'flavor_complexity', 0.0, unixepoch()),
('c740', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'heartiness', 2.5, unixepoch()),
('c741', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'potato_prominence', 4.0, unixepoch()),
('c742', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'novelty', 2.0, unixepoch()),
('c743', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'elegance', -2.0, unixepoch()),
('c744', '2e6b4457-6c93-4323-a91a-ff8266b30b69', 'customizability', -0.5, unixepoch()),

-- Salchipapa (faa61fbe-7bf1-495e-a4bc-d00c38bba754)
('c745', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'crispiness', 3.5, unixepoch()),
('c746', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'richness', 2.0, unixepoch()),
('c747', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'flavor_complexity', 0.5, unixepoch()),
('c748', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'heartiness', 2.5, unixepoch()),
('c749', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'potato_prominence', 2.5, unixepoch()),
('c750', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'novelty', 1.0, unixepoch()),
('c751', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'elegance', -4.0, unixepoch()),
('c752', 'faa61fbe-7bf1-495e-a4bc-d00c38bba754', 'customizability', 0.5, unixepoch()),

-- Salt potatoes (bee560c0-5e89-4467-983e-4a82c143dbf7)
('c753', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'crispiness', -1.5, unixepoch()),
('c754', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'richness', -1.5, unixepoch()),
('c755', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'flavor_complexity', -2.5, unixepoch()),
('c756', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'heartiness', 1.0, unixepoch()),
('c757', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'potato_prominence', 5.0, unixepoch()),
('c758', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'novelty', 0.5, unixepoch()),
('c759', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'elegance', -1.5, unixepoch()),
('c760', 'bee560c0-5e89-4467-983e-4a82c143dbf7', 'customizability', -2.0, unixepoch()),

-- Samosa (176f86ec-6966-43a2-ba73-f872248d7a7c)
('c761', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'crispiness', 4.0, unixepoch()),
('c762', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'richness', 1.0, unixepoch()),
('c763', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'flavor_complexity', 2.5, unixepoch()),
('c764', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'heartiness', 0.5, unixepoch()),
('c765', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'potato_prominence', 2.5, unixepoch()),
('c766', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'novelty', -2.0, unixepoch()),
('c767', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'elegance', -2.0, unixepoch()),
('c768', '176f86ec-6966-43a2-ba73-f872248d7a7c', 'customizability', -1.5, unixepoch()),

-- Schupfnudel (8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb)
('c769', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'crispiness', -1.5, unixepoch()),
('c770', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'richness', 1.5, unixepoch()),
('c771', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'flavor_complexity', -1.0, unixepoch()),
('c772', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'heartiness', 2.0, unixepoch()),
('c773', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'potato_prominence', 4.0, unixepoch()),
('c774', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'novelty', 2.0, unixepoch()),
('c775', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'elegance', -0.5, unixepoch()),
('c776', '8bdf10a9-5e61-4fc4-9d76-fabe8d9cfbfb', 'customizability', -0.5, unixepoch()),

-- Silesian dumplings (6b3159a2-eaf7-4582-8926-fc96ded4d716)
('c777', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'crispiness', -4.0, unixepoch()),
('c778', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'richness', 2.0, unixepoch()),
('c779', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'flavor_complexity', -1.0, unixepoch()),
('c780', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'heartiness', 2.5, unixepoch()),
('c781', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'potato_prominence', 4.5, unixepoch()),
('c782', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'novelty', 2.5, unixepoch()),
('c783', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'elegance', -0.5, unixepoch()),
('c784', '6b3159a2-eaf7-4582-8926-fc96ded4d716', 'customizability', -1.5, unixepoch()),

-- Spice bag (cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7)
('c785', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'crispiness', 4.0, unixepoch()),
('c786', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'richness', 2.0, unixepoch()),
('c787', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'flavor_complexity', 2.5, unixepoch()),
('c788', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'heartiness', 2.5, unixepoch()),
('c789', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'potato_prominence', 2.5, unixepoch()),
('c790', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'novelty', 2.0, unixepoch()),
('c791', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'elegance', -4.0, unixepoch()),
('c792', 'cc226069-c2f9-42d6-bfe2-8bcb9ccb54f7', 'customizability', -0.5, unixepoch()),

-- Steak frites (8fd9f188-564d-462d-8382-ca426986ae96)
('c793', '8fd9f188-564d-462d-8382-ca426986ae96', 'crispiness', 3.5, unixepoch()),
('c794', '8fd9f188-564d-462d-8382-ca426986ae96', 'richness', 2.5, unixepoch()),
('c795', '8fd9f188-564d-462d-8382-ca426986ae96', 'flavor_complexity', 1.0, unixepoch()),
('c796', '8fd9f188-564d-462d-8382-ca426986ae96', 'heartiness', 4.5, unixepoch()),
('c797', '8fd9f188-564d-462d-8382-ca426986ae96', 'potato_prominence', 2.0, unixepoch()),
('c798', '8fd9f188-564d-462d-8382-ca426986ae96', 'novelty', -2.0, unixepoch()),
('c799', '8fd9f188-564d-462d-8382-ca426986ae96', 'elegance', 2.0, unixepoch()),
('c800', '8fd9f188-564d-462d-8382-ca426986ae96', 'customizability', -1.0, unixepoch()),

-- Sweetened potato casserole (99de5a25-6e0f-4386-aecd-d184cc88ff7b)
('c801', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'crispiness', -2.0, unixepoch()),
('c802', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'richness', 3.0, unixepoch()),
('c803', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'flavor_complexity', -1.0, unixepoch()),
('c804', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'heartiness', 2.5, unixepoch()),
('c805', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'potato_prominence', 3.5, unixepoch()),
('c806', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'novelty', 1.0, unixepoch()),
('c807', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'elegance', -1.5, unixepoch()),
('c808', '99de5a25-6e0f-4386-aecd-d184cc88ff7b', 'customizability', -1.5, unixepoch()),

-- Tombet (439bcad0-072b-49fb-9ccc-41ba20f91c85)
('c809', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'crispiness', 0.5, unixepoch()),
('c810', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'richness', 1.5, unixepoch()),
('c811', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'flavor_complexity', 2.0, unixepoch()),
('c812', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'heartiness', 2.5, unixepoch()),
('c813', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'potato_prominence', 3.5, unixepoch()),
('c814', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'novelty', 3.0, unixepoch()),
('c815', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'elegance', 0.5, unixepoch()),
('c816', '439bcad0-072b-49fb-9ccc-41ba20f91c85', 'customizability', -2.0, unixepoch()),

-- Tornado potato (d74cf91f-e373-48bc-a214-5b4bb31d76cf)
('c817', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'crispiness', 4.5, unixepoch()),
('c818', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'richness', 0.5, unixepoch()),
('c819', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'flavor_complexity', -0.5, unixepoch()),
('c820', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'heartiness', -1.5, unixepoch()),
('c821', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'potato_prominence', 5.0, unixepoch()),
('c822', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'novelty', 1.5, unixepoch()),
('c823', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'elegance', -2.5, unixepoch()),
('c824', 'd74cf91f-e373-48bc-a214-5b4bb31d76cf', 'customizability', -2.0, unixepoch());
